### ISSUE TITLE
Investigate automating lein installation with distutils

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#10]
It might be possible to make ``lein`` installation an automated step using distutils. This is worth investigating because it could make setup that much easier. ``java`` would still be a requirement, but that can safely be assumed to be handled by operating system package managers. Alternatively, we could just bundle a shell script with the quickstart project that downloads & installs ``lein``.

**Comment by dan-blanchard** [comment]
The conda recipe I put together in #105 will automatically install Leiningen, and I think that is probably the more appropriate way to solve this issue for now.  This also won't be a factor if/when we get rid of the Clojure part (as per #136).  In light of both of these facts, I'm closing this for now.
