### ISSUE TITLE
Switch from docopt to click or argparse for sparse

### ISSUE THREAD

**Issue by dan-blanchard** [Parsely/streamparse#115]
I know docopt is pretty popular at Parse.ly, but it doesn't offer great usability for something like `sparse` that has several subcommands.

For example, I would fully expect:

```
sparse run --help
```

to give me some `run`-specific, help, but it doesn't, and just prints out the whole giant usage string.  The more commands we add, the worse this situation gets, as people just have to guess what the commands are for.

[Click's `click.command()` decorator](http://click.pocoo.org/4/) seems like a much nicer option for handling many commands,, although even just basic `argparse` is better suited to the task than docopt.

**Comment by dan-blanchard** [comment]
![Poke poke](http://xsreality.org/files/placeimages/2014/99577-political-cartoons.jpg)

**Comment by amontalenti** [comment]
`click` came out in Apr 2014, which was a bit after I started working on streamparse's CLI. I am not opposed to switching to it. `docopt` was the best option back then, `click` may be the best one now -- and hopefully a new one isn't released in 2016 :unamused:

**Comment by dan-blanchard** [comment]
> I am not opposed to switching to it.

I'll take that as permission to put together a PR. :trollface:

**Comment by amontalenti** [comment]
Permission granted!

**Comment by hodgesds** [comment]
I've been hacking on a argparse branch a little bit. Still has a bit to go though.....
https://github.com/hodgesds/streamparse/tree/argparse-refactor

**Comment by dan-blanchard** [comment]
@hodgesds I like that general approach.  It would cut out an unnecessary external dependency for us.

**Comment by dan-blanchard** [comment]
Closed by #152.
