### ISSUE TITLE
Docs: For Storm UI, describe relationship between executors, tasks, and workers for Python

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#118]
In trying to explain Storm to a newcomer and how it maps out to Python processes, I myself got tripped up on the differences between slots, executors, tasks, and workers as shown in Storm UI. It would be good for us to have a part of the Quickstart that explains this.

**Comment by dan-blanchard** [comment]
http://streamparse.readthedocs.org/en/master/topologies.html#parallelism-and-workers
