### ISSUE TITLE
The "error" command isn't supported on ShellSpout

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#121]
So, `ShellBolt` can handle the "error" command, as shown in this file in Storm source code:

https://github.com/apache/storm/blob/2dd7a9426e5634211f14cf5c4e10e021d3420c3c/storm-core/src/jvm/backtype/storm/task/ShellBolt.java#L330

Meanwhile, `ShellSpout` does not actually have a handler for "error". I was pretty surprised by this!

https://github.com/apache/storm/blob/2dd7a9426e5634211f14cf5c4e10e021d3420c3c/storm-core/src/jvm/backtype/storm/spout/ShellSpout.java#L153-L175

What's going on here? Is this just a bug in Storm? Should we submit a pull request to add handling to `ShellSpout`? cc @kbourgoin @msukmanowsky @dan-blanchard

**Comment by dan-blanchard** [comment]
I'm 100% in favor of saying this is a bug in Storm and submitting a PR to them.

**Comment by amontalenti** [comment]
Also, confirmed that storm.py actually does contain a call to `reportError()` (which sends the error command) for the Spout.

https://github.com/apache/storm/blob/2dd7a9426e5634211f14cf5c4e10e021d3420c3c/examples/storm-starter/multilang/resources/storm.py#L259-L260

**Comment by dan-blanchard** [comment]
Other Storm PR I've been meaning to work on is to have it so the whole topology context gets sent to shell bolts (including where its inputs came from and outputs go), since that's available to Java ones.

**Comment by amontalenti** [comment]
@dan-blanchard OK, forked Storm locally and I'm going to implement this patch and submit a PR. Should be easy. Can't believe no one in the community has noticed this till now!

**Comment by amontalenti** [comment]
BTW, I have a fix for this locally and am just putting it through the paces of maven / JUnit tests. Then I'll open ticket & PR on Storm side. Was pretty easy in the end.

**Comment by dan-blanchard** [comment]
Awesome! :+1:

**Comment by dan-blanchard** [comment]
@amontalenti Have you opened a PR for this with Storm yet? Just curious.

**Comment by amontalenti** [comment]
JIRA issue upstream at Storm:
https://issues.apache.org/jira/browse/STORM-796

Pull request:
https://github.com/apache/storm/pull/533

**Comment by amontalenti** [comment]
The PR was merged in https://github.com/apache/storm/pull/533; cc @dan-blanchard

**Comment by dan-blanchard** [comment]
:tada: :tada:

**Comment by hellais** [comment]
Just stumbled into this issue. Happy to see the patch merged upstream! :+1:
