### ISSUE TITLE
sparse run should default to infinite running (also, -t 0)

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#122]
So, a lot of newbies to streamparse step on the landmine that `sparse run` defaults to running for only 5 seconds. We originally chose this value because CTRL+C signals didn't work as reliably with earlier versions of streamparse, but it consistently works these days to shutdown the topology. I was just helping @omus with a streamparse project he's working on and this bit him pretty badly -- he was blaming himself for the Storm shutdown signal being sent after the timer by streamparse.

Here's what should change. I think the default value of "-t" should be 0. In this context, 0 means infinity, that is, run forever. Documentation and CLI options should be updated. This will affect both the "sparse run" docopt handler in Python and the "sparsej run" Clojure handler, as well. I am glad to help anyone who volunteers for this issue w/ the Clojure portion. cc @cabiad

**Comment by dan-blanchard** [comment]
:+1: :+1: :+1: I have been bitten by this many times in the past.

**Comment by jofusa** [comment]
:+1:

**Comment by jofusa** [comment]
For the other newbs finding this thread.

currently the cmd

    sparse run -t 0

shuts down the cluster immediately

    sparse run -t -1 

Runs it forever.

**Comment by greggilbert** [comment]
Just submitted a pull request to update the documentation to reflect this.
