### ISSUE TITLE
Move away from Clojure

### ISSUE THREAD

**Issue by dan-blanchard** [Parsely/streamparse#136]
@amontalenti and I were struggling with getting the Clojure part of streamparse compiled and deployed to clojars because of typical JVM dependency issues, and it made me think it would be nice if we were a pure-Python package.  I know the official thrift binding for Python are horrible to get installed and working properly, but thriftpy is actually a really nice package, and [I made it compatible with the Storm thrift spec](https://github.com/eleme/thriftpy/pull/14) a while ago.

The approach I'm imagining would use the REST API for most things and only use the Thrift interface to Nimbus for submitting a topology.

One downside I see is that unless the user also had the storm CLI installed locally, they wouldn't be able to run a local topology like you currently can with `sparse run`.

**Comment by amontalenti** [comment]
Stuff Clojure is used for right now:

1. Clojure DSL (`streamparse.specs`) that build an in-memory Topology DAG
2. Scripting `StormSubmitter` which uploads JAR to Nimbus along with DAG specification (powers `sparse submit`)
3. Running a `LocalCluster` for local testing (powers `sparse run`)
4. Topology management (`sparse list` and `sparse kill`)

It seems like 1-3 are the "hard ones" to remove/relocate, whereas 4 is easy (just use the HTTP API). 

It's possible that 1 could be replaced by a combination of #84 and an integration with ThriftPy. It's also possible that 2 could be replaced with some ThriftPy code, but if I remember right, the dance required to get the JAR over to the server **and** your topology DAG configured server-side is a little tricky to get right. It seems like 4 would need something in Java, or we'd need to spin it out into its own tool. Studying the way Petrel did things for 1-3 will be instructive.

**Comment by dan-blanchard** [comment]
This slightly out of date page will be a useful reference:  [Lifecycle of a Storm Topology](http://storm.apache.org/documentation/Lifecycle-of-a-topology.html).

**Comment by dan-blanchard** [comment]
Also Nathan Marz's comments on [this Storm issue](https://issues.apache.org/jira/browse/STORM-561) are a good reference for how we could do things just using Thrift.  Even Petrel had some JVM code, which I think we should be able to get around entirely using the approach Nathan outlines.

> Storm's Thrift interfaces allow you to:
>  1. Create spout and bolt object of any language implementation from any other language. The ComponentObject struct can be specified either as a serialized java object, a java class name + arguments, or as a ShellComponent (for running spouts/bolts via subprocesses to allow for other languages).
>  2. Define topologies from any language. Storm gets this for free by the nature of topologies being Thrift objects.
>  3. Submit topologies from any language. Again, Storm gets this for free by the nature of Nimbus being a Thrift server and topologies being Thrift objects.

**Comment by dan-blanchard** [comment]
> It seems like 3 would need something in Java, or we'd need to spin it out into its own tool.

I think for local testing the simplest way to handle that would be to either:

1.  Just provide a Vagrantfile (like we already do for the `kafka-jvm` example) with a Storm instance that people can submit to.
2.  Require people to have the Storm CLI installed somewhere on their PATH and just put together a little wrapper script that starts up nimbus and zookeeper locally.  This is actually the approach the [node-storm library](https://www.npmjs.com/package/node-storm) takes, and I think it's pretty reasonable.

**Comment by dan-blanchard** [comment]
Wow, thriftpy is kind of amazing.  I haven't done much with this yet, but even just playing around for a few minutes, I've got a working Nimbus client in just a few lines of code:

```python
import thriftpy
thriftpy.install_import_hook()
import storm_thrift  # This only works if the storm.thrift file is in the current directory

client = thriftpy.make_client(Nimbus, host='streamparse-box', port=6627,
                              proto_factory=thiftpy.protocol.TBinaryProtocolFactory(),
                              trans_factory=thiftpy.transport.TFramedTransportFactory())

client.getClusterInfo()

Out[25]: ClusterSummary(supervisors=[SupervisorSummary(uptime_secs=31518,
                                                       version='VERSION_NOT_PROVIDED', 
                                                       num_workers=7, 
                                                       num_used_workers=2,
                                                       supervisor_id='021d3edb-6058-4773-90c2-8174135af976', 
                                                       host='precise64')],
                        nimbus_uptime_secs=31521, 
                        topologies=[TopologySummary(num_executors=5,
                                                    num_workers=2, 
                                                    status='ACTIVE', 
                                                    owner=None, 
                                                    uptime_secs=207198, 
                                                    id='pixelcount-4-1429636994', 
                                                    sched_status=None,
                                                    num_tasks=5, 
                                                    name='pixelcount')])

**Comment by msukmanowsky** [comment]
Wow, that is pretty sweet! I'm still kind of confused how thriftpy does all it's magic without any compilation but good sign!

**Comment by dan-blanchard** [comment]
thriftpy is a Python thrift parser combined with Python (and Cython) implementations of the Thrift transport protocols.  It also has some sweet helper stuff for doing RPC, since that's the main thing people use Thrift for.

Also, I'm looking at the Nimbus thrift service some more, and I think you may actually be able to upload any kind of file to it, not just jars.  That could come in handy.

**Comment by dan-blanchard** [comment]
I take that last comment about uploading back.  When you call `beginFileUpload` from the client, the server returns the location of where it's going to save things, and that's a jar.  Oh well, no getting away from jars.

**Comment by kbourgoin** [comment]
If we did get away from jars, wouldn't that hurt our ability to use JVM bolt/spouts too?

**Comment by dan-blanchard** [comment]
Yeah, but I was just imagining simplifying things in the cases where people were submitting pure Python topologies.

We already require people to have Java installed, so as long as we just keep that requirement, we can create jars pretty easily with the `jar` command.

**Comment by sixers** [comment]
I suggested using Py4J here: #84 

This would help us to be more Pythonic, but allow flexibility in combining Python and JVM based components.

What do you think?

**Comment by omus** [comment]
I think having the Storm CLI installed locally is a totally reasonable approach.

**Comment by rduplain** [comment]
I'm treating #84 as the reference for the DSL improvements of streamparse, when discussing project planning.

**Comment by amontalenti** [comment]
By the way, I opened this issue on thriftpy which got addressed by a PR:

https://github.com/eleme/thriftpy/issues/153

That is now working in thrifrpy's develop branch. This makes it possible for streamparse/pystorm to embed a copy of storm.thrift directly inside its Python package in order to get the thriftpy comm layer created at runtime.

**Comment by amontalenti** [comment]
Also, Dan mentioned that local running could require the path to a local Storm installation.

It's worth mentioning that this is the way pyspark works. You set up a local Spark installation, and running "pyspark" is basically running your Python interpreter while Spark backgrounds its own infrastructure (and then makes it available via the "sc" variable in the Python interpreter). Likewise, "spark-submit" in "local" mode just does the same. thing for a standalone run.

I wonder if we could just copy this familiar workflow. Local running would be either a Python shell with access to some kind of StormContext, which would wrap up nimbus comm via Thrift. Submitting in local mode would use the local installation to spin up the appropriate dev servers. All seems do'able to me these days.

**Comment by dan-blanchard** [comment]
I don't think we need to go as far as trying to model everything that Spark is providing (like a context object that you can play with in a Python REPL).  The infrastructure of Storm is too different from Spark to allow for that sort of experimentation where you take some data and apply a bunch of functions to it that magically get executed on the cluster.  With Storm your tuples are always coming out of a spout and then just getting fired through the topology.

Anyway, I really like the idea of just requiring that people have Storm installed.  It simplifies a lot of things.  For example, we could just reuse `storm shell` to submit our Python DSL topologies if we did (although we would probably want to provide a less verbose wrapper around it).

**Comment by dan-blanchard** [comment]
After merging #199, there is no Clojure code in our codebase except for `project.clj` files.
