### ISSUE TITLE
Documentation update for Ubuntu 14.04

### ISSUE THREAD

**Issue by j105rob** [Parsely/streamparse#139]
The quick start process should provide a note to ubuntu 14.04 users, that the Leiningen package provided by the default package repo is very out of date and Lein should be installed from source.

**Comment by rduplain** [comment]
This issue appears to be fixed today. The streamparse quickstart says:

> lein, which you can install from the [project’s page](http://leiningen.org/) or [github](https://github.com/technomancy/leiningen#leiningen)

leiningen.org has a self-installer and specifically gives preference to getting version 2.x, which the `lein` script will do. Grabbing a screenshot for quick reference (go to http://leiningen.org to get clickable links):

![screenshot](https://cloud.githubusercontent.com/assets/36428/8508195/e90d5440-2234-11e5-8a20-b47623fd7c3b.png)

You can use the JDK which ships with Ubuntu 14.04.
