### ISSUE TITLE
spout.py emit_many is broken

### ISSUE THREAD

**Issue by kuribe** [Parsely/streamparse#144]
Hi, 

The method emit_many in spout.py calls repeatedly the emit method and sends across values for anchors; however the signature of emit does not include the field anchors, for that reason the code breaks when emit_many is called. 

Can you fix the issue by adding anchors to the emit method?

Karina

**Comment by dan-blanchard** [comment]
As proposed in #66, `emit_many` will be deprecated in the next release and removed in the one after that.  I would recommend avoiding it entirely and repeatedly calling `emit`.
