### ISSUE TITLE
tick tuples reach regular event stream instead of process_tick

### ISSUE THREAD

**Issue by daTokenizer** [Parsely/streamparse#146]
Tick tupels, according to the documentation are supposed to reach only the bolts overriding process_tick() where thay will be processed. Instead, we see that the tuples reach regular process() function in all bolts, are handled as part of the regular stream, and may interfere with normal behavior.

**Comment by dan-blanchard** [comment]
`process_tick` is only available in the unreleased master branch.  I will hopefully have time to release a new version in the next week or so.

**Comment by daTokenizer** [comment]
can I help in  any way?

**Comment by dan-blanchard** [comment]
Thanks for the offer, but not really.  I just need one of the other committers to review #137, which is the only thing I'm waiting on before doing the release.
