### ISSUE TITLE
kafka-jvm example fails with exit code 11

### ISSUE THREAD

**Issue by lthibault** [Parsely/streamparse#147]
Hello,

I'm trying to get the kafka-jvm example working, but I've hit a bit of a roadblock.  A couple of things have left me confused ...

1. The kafka-jvm example under the master branch claims that the example depends on an unmerged branch, the jvm-example branch seems to have been merged into master.  Is the readme out of date?
2. Setting up the vagrant/virtualbox VM seems to work well and I'm able to ssh into `192.168.50.50`, but `sparse run --debug -t 120` still fails with a cryptic exit code 11.

To be sure, I uninstalled the streamparse version that was installed through `pip install -r requirements.txt`, cloned the streamparse repo, checked out the jvm-example branch and then installed via `python setup.py develop` before retrying the `sparse run` command.

Below is the output generated by `sparse run --debug -t 120 | grep "Emitting: pixel-count-bolt default"` using the version of streamparse installed via `pip install -r requirements.txt`.  As far as I can tell, the problem is identical when using the jvm-example branch.

```
log4j:WARN No appenders could be found for logger (backtype.storm.utils.ShellProcess).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Traceback (most recent call last):
  File "/Users/louist/Desktop/kafka-jvm-dev/env/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/Users/louist/Desktop/kafka-jvm-dev/env/lib/python2.7/site-packages/streamparse/cmdln.py", line 83, in main
    run_local_topology(args["--name"], time, par, options, args["--debug"])
  File "/Users/louist/Desktop/kafka-jvm-dev/env/lib/python2.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/Users/louist/Desktop/kafka-jvm-dev/env/lib/python2.7/site-packages/streamparse/ext/invoke.py", line 182, in run_local_topology
    run(full_cmd)
  File "/Users/louist/Desktop/kafka-jvm-dev/env/lib/python2.7/site-packages/invoke/runner.py", line 349, in run
    return runner.run(command, **kwargs)
  File "/Users/louist/Desktop/kafka-jvm-dev/env/lib/python2.7/site-packages/invoke/runner.py", line 153, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!

Exit code: 11

Stderr:

log4j:WARN No appenders could be found for logger (backtype.storm.utils.ShellProcess).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
The problem appears to be (at least partly) related to invoke.  What gives?

**Comment by brandomr** [comment]
getting the same error myself. Will let you know if I resolve

**Comment by wrrwhn** [comment]
does any solution for it ?

**Comment by dan-blanchard** [comment]
Did you follow all the instructions in the [README](https://github.com/Parsely/streamparse/tree/master/examples/kafka-jvm#3-modify-etchosts)? It sounds to me like it's probably an issue with your SSH settings, or possibly the `/etc/hosts` change you need to make.

**Comment by dan-blanchard** [comment]
> The kafka-jvm example under the master branch claims that the example depends on an unmerged branch, the jvm-example branch seems to have been merged into master. Is the readme out of date?

I must have updated it since you saw that, because I don't see that anymore.

**Comment by dan-blanchard** [comment]
I think this was just a matter of outdated instructions, so I'm closing this.
