### ISSUE TITLE
Make workers configurable within submit_topology.clj

### ISSUE THREAD

**Issue by alexlovelltroy** [Parsely/streamparse#15]
[submit_toplogy](https://github.com/Parsely/streamparse/blob/master/jvm/src/streamparse/commands/submit_topology.clj#L21) is hard coded to use three workers.  Someone might want to change that number.

**Comment by amontalenti** [comment]
Closing this issue as we actually did implement the reported issue but there is a separate issue discussed, which is externalization of configuration options via YAML or somesuch. Anyway, not related.
