### ISSUE TITLE
Async Spout Support

### ISSUE THREAD

**Issue by hodgesds** [Parsely/streamparse#150]
Need to add async spout base class so that async libraries can be efficiently used as spouts.

**Comment by kbourgoin** [comment]
Can you elaborate on this? I'm not sure what you mean by async libraries being used as spouts.

**Comment by hodgesds** [comment]
I want to poll on a file descriptor(s) for reading/writing and to interface with other asynchronous libraries (ex: libpcap, zmq, nanomsg). The current spout code runs a infinite loop using a while loop and thread locks for IO. I'd like to use something like tornado or asyncio to run an ioloop in the spouts "run" function. I'll have an example branch in the next few days.

**Comment by dan-blanchard** [comment]
Ah, that would be nice.  Maybe we could look into using [trollius](https://pypi.python.org/pypi/trollius), which is a Python 2.7 port of `asyncio`.

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#8
