### ISSUE TITLE
Clojure DSL issues with directing streams

### ISSUE THREAD

**Issue by westover** [Parsely/streamparse#162]
Preface this: I know the Clojure DSL's are going away and I am happy about that. I would much rather use Thrift. And do offer to help support this project in their upstream Thrift endeavors because I am already implementing that on my side.

The problem I am having when I try to follow the resources for the [Clojure DSL](http://storm.apache.org/documentation/Clojure-DSL.html) regarding 
>bolt-spec
>bolt-spec takes as arguments the input declaration for the bolt, the bolt implementation (an object that implements IRichBolt), and optional keyword arguments.
>The input declaration is a map from stream ids to stream groupings. A stream id can have one of two forms:
>[==component id== ==stream id==]: Subscribes to a specific stream on a component
>==component id==: Subscribes to the default stream on a component

Basically I want to create multiple streams from a single bolt for effective routing in my topology. But to use a toy example would be to take the word count example and have the spout or bolt emit a 'dog' only stream.

However when I define a vector for my downstream bolts with explicit keys for streams created in my routing bolt I get errors that they are not defined.

**Comment by rduplain** [comment]
If I understand correctly what you are trying to accomplish, you can use field grouping in the spec. In `topologies/your-project.clj`:

```clojure
    {"search-bolt" (python-bolt-spec
          options
          {"url-spout" ["url"]}
          "birding.bolt.TwitterSearchBolt"
          ["url" "timestamp" "search_result"]
          :p 2
          )
     "lookup-bolt" (python-bolt-spec
          options
          {"search-bolt" ["url"]}
          "birding.bolt.TwitterLookupBolt"
          ["url" "timestamp" "lookup_result"]
          :p 2
          )
    }
```

Emphasis on `{"search-bolt" ["url"]}`. This is from an example project called [birding](https://github.com/Parsely/birding), changing shuffle to field grouping on the `"lookup-bolt"` from [3846cce](https://github.com/Parsely/birding/commit/3846ccec9060c67ce6b20c44104e79d1bac3625a). I just ran this without errors.

**Comment by westover** [comment]
I am trying to bind not to a specific field grouping but rather a stream. Bolts can emit multiple streams and the python bolt component even supports specifying output stream.
```   
 {"search-bolt" (python-bolt-spec
          options
          {"url-spout" ["url"]}
          "birding.bolt.TwitterSearchBolt"
          ["url" "timestamp" "search_result"]
          :p 2
          )
     "lookup-bolt" (python-bolt-spec
          options
          {["search-bolt" "JohnSmith"] ["url"]}
          "birding.bolt.TwitterLookupBolt"
          ["url" "timestamp" "lookup_result"]
          :p 2
          )
    }
```

Where in my bolt I specify something like this

```
def process(tup):
    if tup.values[0] == 'JohnSmith':
        self.emit(tup, stream='JohnSmith')
```

**Comment by rduplain** [comment]
When I run that configuration, I get:

```
InvalidTopologyException(msg:Component: [lookup-bolt] subscribes from non-existent stream: [JohnSmith] of component [search-bolt])
```

My understanding of [Clojure DSL](http://storm.apache.org/documentation/Clojure-DSL.html) (others are welcome to jump in) is that you need to specify the stream ID in the output spec, then use that ID in the input spec:

```clojure
    {"search-bolt" (python-bolt-spec
          options
          ; Use field grouping on URL to support in-memory caching.
          {"url-spout" ["url"]}
          "birding.bolt.TwitterSearchBolt"
          {"JohnSmith" ["url" "timestamp" "search_result"]}
          :p 2
          )
     "lookup-bolt" (python-bolt-spec
          options
          {["search-bolt" "JohnSmith"] ["url"]}
          "birding.bolt.TwitterLookupBolt"
          ["url" "timestamp" "lookup_result"]
          :p 2
          )
```

**Comment by amontalenti** [comment]
Yes, that's right. When stream id's are not specified, both in the DSL and
in emit() calls, it is assumed you are using a single stream, called
"default" internally.

But when stream ID's are specified in a bolt/spout's output, then
downstream bolts can subscribe to that stream using the DSL syntax Ron
demonstrated. To emit on that stream, the components pass the stream ID to
emit() as a kwarg. This mirrors the way Storm's Java API works, and makes
it so for simple topologies, you needn't worry about stream IDs, but for
complex ones, you can have any number and each with separate steam grouping
specs and distinct participation in the topology graph.

-Andrew

**Comment by westover** [comment]
That works perfectly for me. Thanks!!

**Comment by rduplain** [comment]
Shall we consider reopening this to update the docs? The issue discussion should come through on search engines, but there's important info here to capture.
