### ISSUE TITLE
Doc consistency for Bolt/Spout discussion.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#164]
This is a minor issue for documentation consistency. As I work on the docs, I see differing use of capitalization of Storm concepts, mostly Bolt/bolt and Spout/spout. The [Storm Concepts](https://storm.apache.org/documentation/Concepts.html) doc uses lowercase ("A topology is a graph of spouts and bolts that are connected with stream groupings."), so I'll use lowercase in my patches.

If we have consensus, then this issue is just a simple "help wanted" task to make the docs consistent.

**Comment by amontalenti** [comment]
I think the names are unique enough (bolt, spout, topology, tuple) that using lowercase spelling is probably OK. There is a small issue with the fact that a Storm tuple is a different thing than a Python tuple, but that the streamparse representation of a Storm tuple is actually a `Tuple` class with a property that is a `namedtuple` of the actual values... see #127. In fact, as I describe that, I realize this fact itself should be in our docs :)

**Comment by rduplain** [comment]
The Tuple distinction was one of the very first things I noticed when getting into the project. I'll add a note in the docs for that.

**Comment by rduplain** [comment]
The Bolt/bolt and Spout/spout inconsistencies were an easy fix, d5f6cfc695e71824dfdb397afbf1a8848eaa8b65. Unclear on how to be consistent with Tuple/tuple discussion. The narrative docs are consistently lowercase, but the code comments/docs are mixed use. I'll make a quick pass at it.

**Comment by dan-blanchard** [comment]
I usually try to use uppercase when talking about the Python classes (Bolt and Spout), and lowercase otherwise.

**Comment by rduplain** [comment]
> I usually try to use uppercase when talking about the Python classes (Bolt and Spout), and lowercase otherwise.

This was my intent in d5f6cfc695e71824dfdb397afbf1a8848eaa8b65.
