### ISSUE TITLE
java.lang.RuntimeException: Unknown command received: error

### ISSUE THREAD

**Issue by daTokenizer** [Parsely/streamparse#167]
>20542404612 [Thread-40-topx-spout] ERROR backtype.storm.util - Async loop died! java.lang.RuntimeException: Unknown command received: error
>	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:115) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:68) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at backtype.storm.daemon.executor$fn__3284$fn__3299$fn__3328.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at backtype.storm.util$async_loop$fn__452.invoke(util.clj:431) ~[storm-core-0.9.2->incubating.jar:0.9.2-incubating]
>	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
>	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
>2404613 [Thread-40-topx-spout] ERROR backtype.storm.daemon.executor - 
>java.lang.RuntimeException: Unknown command received: error
>	at backtype.storm.spout.ShellSpout.querySubprocess(ShellSpout.java:115) ~[storm-core-0.9.2->incubating.jar:0.9.2-incubating]
>	at backtype.storm.spout.ShellSpout.nextTuple(ShellSpout.java:68) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at backtype.storm.daemon.executor$fn__3284$fn__3299$fn__3328.invoke(executor.clj:563) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at backtype.storm.util$async_loop$fn__452.invoke(util.clj:431) ~[storm-core-0.9.2-incubating.jar:0.9.2-incubating]
>	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
>	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
>2404621 [Thread-40-topx-spout] INFO  backtype.storm.util - Halting process: ("Worker died")
Traceback (most recent call last):

this is a known bug in storm 0.9.2 - which is the version seem to come with sparse.
[it was fixed in 0.9.5 ] (http://stackoverflow.com/questions/30732178/storm-error-async-loop-died)

**Comment by daTokenizer** [comment]
the only question is why changing the storm dependency from `0.9.2-incubating` to `0.9.5` produces this error:
>java.lang.RuntimeException: subprocess heartbeat timeout
>	at backtype.storm.spout.ShellSpout$SpoutHeartbeatTimerTask.run(ShellSpout.java:261) [storm-core-0.9.5.jar:0.9.5]
>	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_51]
>	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_51]
>	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_51]
>	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_51]
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
>	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]

**Comment by dan-blanchard** [comment]
@daTokenizer what version of streamparse are you using?

Also, this is a duplicate of #121.

**Comment by daTokenizer** [comment]
2.0.2 (but started before 2.0.0) -  just realized using quickstart with 2.0.2 the quickstart project.clj does use storm 0.9.5 but just chnging that in my clj causes a heartbeat problem. I am working on it right now, and will let you guys know if i'll find out thee source if it

**Comment by dan-blanchard** [comment]
As of Storm 0.9.3, the Java process that talk communicate to your actual Python bolts/spouts require the Python process to send back a command every so many seconds.  (This is detailed at the bottom of the [multi-lang protocol documentation](https://storm.apache.org/documentation/Multilang-protocol.html), if you're interested.)  If you have a bolt/spout that takes too long to process/generate a tuple, then streamparse cannot acknowledge the heartbeat in time, and your subprocess will be marked dead.  That's what you're seeing happening.

If you have a particular component you know will be slow, you should bump up the Storm `supervisor.worker.timeout.secs` setting for your topology.  You can do that by specifying `--option "supervisor.worker.timeout.secs=600"` when you call `sparse`.  That'll make sure Storm only cares if your Python subprocess doesn't respond within10 minutes.

**Comment by daTokenizer** [comment]
just logged in to say I solved it by making sure the process has ssomthing to process in the intake queue when its starts, and there you go. Thanks Dan! will do that soon.
