### ISSUE TITLE
configuring zookeeper 

### ISSUE THREAD

**Issue by daTokenizer** [Parsely/streamparse#168]
how do you configure the zookeeper instance that sparse is running? 
We are experiencing forceSync under high loads problems and need to change some parameters in it.

>[SyncThread:0] WARN  org.apache.zookeeper.server.persistence.FileTxnLog - fsync-ing the write ahead log in SyncThread:0 took 10617ms which will adversely effect operation latency. See the ZooKeeper troubleshooting guide 

....

>java.nio.channels.CancelledKeyException: null
>	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73) ~[na:1.8.0_51]
>	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77) ~[na:1.8.0_51]
>	at org.apache.zookeeper.server.NIOServerCnxn.sendBuffer(NIOServerCnxn.java:153) [zookeeper-3.4.5.jar:3.4.5-1392090]
>	at org.apache.zookeeper.server.NIOServerCnxn.sendResponse(NIOServerCnxn.java:1076) [zookeeper-3.4.5.jar:3.4.5-1392090]
>	at org.apache.zookeeper.server.FinalRequestProcessor.processRequest(FinalRequestProcessor.java:404) [zookeeper-3.4.5.jar:3.4.5-1392090]
>	at org.apache.zookeeper.server.SyncRequestProcessor.run(SyncRequestProcessor.java:138) [zookeeper-3.4.5.jar:3.4.5-1392090]

**Comment by daTokenizer** [comment]
this bug apperently known and is solved by adding -Dzookeeper.forceSync=no can this be done without hacking streamparse?

**Comment by daTokenizer** [comment]
apparently not:
>Unrecognized option: -client -Dzookeeper.forceSync=no
>Error: Could not create the Java Virtual Machine.

**Comment by dan-blanchard** [comment]
This is more of a server infrastructure problem than a streamparse issue.  You should configure zookeeper according to [their docs](https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html) (i.e., you should modify `conf/zoo.cfg` wherever you have zookeeper installed).
