### ISSUE TITLE
Qualify version between releases (e.g. 3.0-dev).

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#175]
The current HEAD of master has its version in the code set to `'2.0.2'`, though it's several commits beyond the release -- `git describe` currently says `v2.0.2-26-gf4ec238`. The [encoded version](https://github.com/Parsely/streamparse/blob/d9f23d96b280697a6f6775161dd3fa5f4ee0d5ae/streamparse/version.py) should be a qualification against the upcoming release as soon as a release is tagged, as to mitigate confusion where your installation reports a tagged version when you are actually running against a git checkout.

**Comment by rduplain** [comment]
Here's [one such example commit](https://github.com/mitsuhiko/flask/commit/d94b1bec24f47e5997787f5ee762d8b2566d81b4).

**Comment by dan-blanchard** [comment]
I like this idea.  It's just a matter of getting into the habit after we do releases.

**Comment by dan-blanchard** [comment]
I'm doing this now for this and pystorm.
