### ISSUE TITLE
Fully support Python 3.4.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#176]
There are several closed issues which resolve with (usually @dan-blanchard saying):

> You just need to install the Python 3 compatible fork of fabric in our [requirements.txt](https://github.com/Parsely/streamparse/blob/08ef3d461243c6dc906f8773c84dc0140200a395/requirements.txt#L2).

https://github.com/Parsely/streamparse/issues/86#issuecomment-101348677 is currently the most useful doc for this. Even the [FAQ](http://streamparse.readthedocs.org/en/master/faq.html#is-streamparse-compatible-with-python-3) from the docs says:

> Yes, streamparse is fully compatible with Python 3 starting with version 3.3 which we use in our [unit tests](https://github.com/Parsely/streamparse/blob/master/.travis.yml).

A short-term fix would be to make the docs clearer about the `requirements.txt` usage. A longer-term fix is to drop Fabric altogether, as discussed in #45 where #99 is relevant.

**Comment by dan-blanchard** [comment]
`fabric3` is what we rely on now, so this can be closed.
