### ISSUE TITLE
BatchingBolt which is volume-based, not time-based.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#182]
The current BatchingBolt implementation is based on the number of ticks. A variant could accumulate tuples (or even values contained in those tuples) until a certain threshold is hit (e.g. every 100 tuples). This would be useful when e.g. batching to an upstream/downstream service that is rate-limited, as to send a full request.

This would likely need some time-delay featured in which the threshold is ignored after a certain wait, as to avoid holding onto values indefinitely if the threshold is never hit.

**Comment by dan-blanchard** [comment]
This would be pretty easy to setup.  We'd just need to split the check on [this line](https://github.com/Parsely/streamparse/blob/f4ec2383277fcc5172313c2585d23b653f153306/streamparse/storm/bolt.py#L366) out into its own method called `BatchingBolt.is_batch_ready()` (or something like that).  We could then just have the default implementation be:

```python
def is_batch_ready(self):
    return self._tick_counter > self.ticks_between_batches and self._batches
```

Then in your `ThresholdBatchingBolt` subclass you would just need to override that one method as:

```python
def is_batch_ready(self):
    if self._batches:
        num_tuples = sum(len(batch) for batch in itervalues(self._batches))
        return (num_tuples >= self.batch_threshold or 
                super(ThresholdBatchingBolt, self).is_batch_ready())
    else:
        return False
```

That'll give you an implementation that will fallback on time if the size threshold isn't met, so you just need to make sure you set `ticks_between_batches` high enough.

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#2
