### ISSUE TITLE
Consider "napoleon" style of docstrings.

### ISSUE THREAD

**Issue by rduplain** [Parsely/streamparse#185]
http://sphinx-doc.org/ext/napoleon.html

> Napoleon is a pre-processor that parses [NumPy](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) and [Google](http://google-styleguide.googlecode.com/svn/trunk/pyguide.html#Comments) style docstrings and converts them to reStructuredText before Sphinx attempts to parse them.

**Comment by dan-blanchard** [comment]
scikit-learn uses numpy-style docstrings, and they're certainly much easier to read for long lists of parameters.  I'm not sure we have any methods that take enough parameters for this to really be an issue though.

**Comment by rduplain** [comment]
In my opinion, streamparse has dense enough docstrings to benefit from a move to "napoleon" style, e.g. [Component]( https://github.com/Parsely/streamparse/blob/7105f7786bbeaa4c1f15998dbec97f496e15af21/streamparse/storm/component.py#L131). pykafka especially needs it, e.g. [BalancedConsumer](https://github.com/Parsely/pykafka/blob/18b55ae9703347a81af9fe42ad644f4c2b0ca291/pykafka/balancedconsumer.py#L41).

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#4
