### ISSUE TITLE
Add readthedocs link to repo description

### ISSUE THREAD

**Issue by jasonrhaas** [Parsely/streamparse#187]
As of now, there isn't a link to http://streamparse.readthedocs.org on https://github.com/Parsely/streamparse.  Might be helpful to add it to the repo description or the README file.

**Comment by jasonrhaas** [comment]
nevermind, I see the it under the HEAD link.  I didn't look very hard.

**Comment by amontalenti** [comment]
The link is right here: https://github.com/Parsely/streamparse/blob/master/README.rst#documentation
