### ISSUE TITLE
JVM configuration for heap size and garbage collection parameters

### ISSUE THREAD

**Issue by tanaysoni** [Parsely/streamparse#188]
Since `streamparse` executes topologies as Java processes, I was wondering if it is possible to configure JVM parameters like initial and maximum heap size(I want to make garbage collection more aggressive to save on memory). A documentation of it with examples of Java configurations will be useful for all.

**Comment by msukmanowsky** [comment]
Hi @tanaysoni, streamparse already supports this by allowing you to pass Storm configuration options via your topology definition. I'll admit better documentation here is definitely needed but here's a quick example to get you over the hump.

A list of all Storm config options is available [here](https://storm.apache.org/javadoc/apidocs/backtype/storm/Config.html) but the options you're looking for are likely [WORKER_CHILDOPTS](https://storm.apache.org/javadoc/apidocs/backtype/storm/Config.html#WORKER_CHILDOPTS), or [TOPOLOGY_WORKER_CHILDOPTS](https://storm.apache.org/javadoc/apidocs/backtype/storm/Config.html#TOPOLOGY_WORKER_CHILDOPTS).

From the docs, sounds as though TOPOLOGY_WORKER_CHILDOPTS is the one to use when submitting topologies and that WORKER_CHILDOPTS is probably best managed from your `storm.yaml`.

To set this param on a streamparse deploy, you can do something like:

```
> sparse submit -n my_topology -o worker.topology_worker_childopts "-Xms<size> -Xmx<size>"
```

Not 100% sure that `worker.topology_worker_childopts` will work, give it a shot and let me know.

**Comment by andrewkcarter** [comment]
I'm running into difficulty when using options that contain an '=' character. This is the command I'm running after trying several quoting variations...
`sparse submit -n my-topology --option "'worker.childopts=\"-Xmx256m -XX:PermSize=64m -XX:MaxPermSize=256m -Xms64m\"'"`

It looks like it's going into the lein command correctly (last line)...
`Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/my-topology.clj --host vagrant-ist-01 --port 6627 --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/tmp/virtualenvs/my-topology/bin/python"' --option 'streamparse.log.path="/var/log/storm"' --option 'streamparse.log.max_bytes=1000000' --option 'streamparse.log.backup_count=10' --option 'streamparse.log.level="info"' --option 'worker.childopts="-Xmx256m -XX:PermSize=64m -XX:MaxPermSize=256m -Xms64m"'`

But the storm submitter has mangled it at the '=' in the perm size parameter (last line):
`2686 [main] INFO  b.s.StormSubmitter - Successfully uploaded topology jar to assigned location: /var/storm/nimbus/inbox/stormjar-8860275d-c760-4ba5-a562-a6d9430d80b1.jar
2687 [main] INFO  b.s.StormSubmitter - Submitting topology email-processor in distributed mode with conf {"storm.zookeeper.topology.auth.scheme":"digest","streamparse.log.backup_count":10,"storm.zookeeper.topology.auth.payload":"-6607125013727628424:-8189612296606544246","streamparse.log.path":"\/var\/log\/storm","topology.python.path":"\/tmp\/virtualenvs\/my-topology\/bin\/python","topology.debug":false,"nimbus.thrift.port":6627,"topology.max.spout.pending":5000,"nimbus.host":"vagrant-ist-01","topology.workers":2,"topology.acker.executors":2,"streamparse.log.max_bytes":1000000,"streamparse.log.level":"info","worker.childopts":"\"-Xmx256m -XX:PermSize","topology.message.timeout.secs":60}`

Is there something I can do differently with escaping or quoting?
