### ISSUE TITLE
six>=1.5 as requirement

### ISSUE THREAD

**Issue by shottedsheriff** [Parsely/streamparse#190]
With Mac, there is an issue with using streamparse if six version is too low. Not sure if it has to be >=1.5 but the default six from OS X Yosemite, 1.4.1 didn't work with streamparse. The exact problem is with 'from six.moves.socketserver import ..'. It can't import six.moves.socketserver. I can see that pip install six so the problem is that the old one is still being used. Is it the problem everyone should handle themselve or could installation script do something about that?

**Comment by dan-blanchard** [comment]
`streamparse` should be installed in a virtualenv or conda environment on OS X.  You should basically never pip install things into the default Python installation in `/Library` as that can break all sorts of things that you might not expect.  See comments on issue #113.  

I will update our `requirements.txt` to make the six >= 1.5 dependency explicit.
