### ISSUE TITLE
pip version and options

### ISSUE THREAD

**Issue by sujaymansingh** [Parsely/streamparse#194]
I have a streamparse project which needs to install privately hosted python packages.

As such, I need/want to use a recent version of pip (which supports `--process-dependency-links`).

I can have my script that provisions the storm workers add a pip config file that has `process-dependency-links=yes`, but that isn't used by pip 1.5.

Is there any easy way I can make `sparse submit` install a different version of pip before trying to install the requirements?

**Comment by amontalenti** [comment]
@sujaymansingh Sorry for delay on responding.

You can definitely install a different version of pip on your workers before `sparse submit`. The streamparse remote execution logic currently uses whatever version of `pip` is actually on the `$PATH` for the user that logs into your remote worker nodes. So if you merely `pip install -U pip` on each worker node once, that will upgrade pip and you can start using your own.

There is not currently a built-in way to modify the specific `pip` command that `sparse submit` uses. It's just resolved on the $PATH, as mentioned.

You may also be interested in [this FAQ entry](http://streamparse.readthedocs.org/en/latest/faq.html#how-do-i-trigger-some-code-before-or-after-i-submit-my-topology) which discusses how by providing your own `fabfile.py` in your project folder, you can hook into `pre_submit` and `post_submit` Fabric hooks to put your own logic in place. We use this to customize steps that happen before and after `sparse submit` runs.

**Comment by sujaymansingh** [comment]
No problem @amontalenti 

Thanks for the suggestion about upgrading pip on the boxes.

I did have a quick look at the `fabfile.py`, but that runs before adding hosts the the `fabric.env.hosts` variable. (Although I can easily add something that parses the `config.json` file.)

I'm going to try the global pip upgrade, as that sounds like it would work well.
