### ISSUE TITLE
Add ability to swallow I/O errors

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/streamparse#198]
When monitoring streamparse topologies with tools like Sentry, receiving tons of errors like:

```
Received EOF while trying to read stdin from Storm, pipe appears to be broken, exiting.
Error streamparse.storm.component in read_messagestreamparse.ipc
```

Lead to alerting fatigue (we've had 5.9K of these in just one of our production topologies, as @dan-blanchard knows :)). The IPC layer shutting down like this, is usually because of another issue like some other component dying and Storm killing components or rebalancing a topology. In the former case, the actual exception is captured elsewhere already, in the latter, it's a non-error. Either way, the utility of the IPC exception is questionable.

My gut instinct is just swallow these exceptions full stop, but maybe others have use for them. Ideas on how to handle the ability to stop these from being raised?

**Comment by dan-blanchard** [comment]
I'm going to move this issue over to pystorm, since that's where all the IPC code lives now.  I'll make more comments after that.

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#12
