### ISSUE TITLE
call to unbound fn error when submitted to storm cluster but run locally fine

### ISSUE THREAD

**Issue by eencdl** [Parsely/streamparse#200]
When I ran it locally it was ok (sparse run -d) but when it is submitted to STORM cluster, I got

java.lang.RuntimeException: java.lang.IllegalStateException: Attempting to call unbound fn

clojure version is 1.5.1, storm version is 0.9.5, sparse 2.1.3

the error was due to calling "call-to-outside-function" within spout execute, and sometime the function can be 3rd party as well, the code is as follows:

```clj
(defn call-to-outside-function \[someArg\] (print "something"))

(defspout kw-spout \["something"\]
  \[conf context collector\]
        (spout
            (nextTuple []
                (Thread/sleep 100)
                (call-to-outside-function "someArgs")
                (emit-spout! collector ("not important"))
                )
            (ack [id])
            ))
```

Not sure if this is a bug in streamparse or STORM or both or my lack of understanding.

**Comment by dan-blanchard** [comment]
While we certainly support spouts and bolts written in Clojure, we're not actually Clojure experts ourselves.  This question would be better suited to the official Storm mailing list, as it looks like it's simply an issue with your code.
