### ISSUE TITLE
"workers" key in config.json does not seem to be working

### ISSUE THREAD

**Issue by tanaysoni** [Parsely/streamparse#201]
Here's my config.json file:
```json
{
    "library": "",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "test": {
            "user": "storm",
            "nimbus": "localhost",
            "workers": ["x.x.x.x"],
            "log": {
                "path": "",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "use_ssh_for_nimbus": false,
            "virtualenv_root": "/home/ubuntu/.virtualenvs/storm/"

        }
    }
}
```

No matter what I set the value of `workers`, the topology gets submitted to the Storm running on localhost(I intend to submit it to the Storm running at x.x.x.x). There's no error message generated even on supplying fictions IP addresses for workers. What I may be doing wrong here?

**Comment by dan-blanchard** [comment]
Thanks for reporting this issue.  It's a new one to me.

Just out of curiosity, do you get a different result if you set `use_ssh_for_nimbus` to true?

**Comment by dan-blanchard** [comment]
Oh wait, sorry, I misread your message.

`workers` is only used for setting which machines need virtualenvs created on them.  The `nimbus` setting is where your topology will be submitted (and then it's up to Storm/Nimbus to decide which machines things actually get executed on).

#158 has a short discussion of a related issue that might be informative to you.

**Comment by dan-blanchard** [comment]
Your issue also relates to the fact that we need to add config validation in the future (as in #173).

**Comment by tanaysoni** [comment]
1. Since the `workers` is used for setting machines on which virtualenvs has to be setup, we could add in the documentation that `workers` key is irrelevant when `use_virtualenv` is set to `false`. 
1. From what I understood, there's no way to `sparse submit` a topology such that it gets executed on a specific machine running Storm. This functionality could be useful if you'd want to execution of topologies to happen on different isolated machines.

**Comment by dan-blanchard** [comment]
> Since the `workers` is used for setting machines on which virtualenvs has to be setup, we could add in the documentation that `workers` key is irrelevant when `use_virtualenv` is set to `false`.

I completely agree that we should do that.

> From what I understood, there's no way to `sparse submit` a topology such that it gets executed on a specific machine running Storm. This functionality could be useful if you want execution of topologies to happen on different isolated machines.

That's an interesting idea, but I'm not sure it's one we could make work, because Storm's Nimbus process decides which machines things execute on.  It's just how the Storm cluster architecture is setup.
