### ISSUE TITLE
Python libraries

### ISSUE THREAD

**Issue by Ulitochka** [Parsely/streamparse#208]
Hello.
Thanks for your work.

My question is: can I use in bolts / spouts python libraries like numpy, scipy or scrapy?

**Comment by dan-blanchard** [comment]
Yes, you just need to specify a requirements file in your project's `virtualenvs` directory with the same name as your topology.  See the [quickstart docs](http://streamparse.readthedocs.org/en/master/quickstart.html#project-structure).
