### ISSUE TITLE
Integration python and java

### ISSUE THREAD

**Issue by Ulitochka** [Parsely/streamparse#209]
Hello.
I have a question related to the integration python and java.
How python code executed on separate machines? The python interpreter runs on each bolt and spout on each machine?

**Comment by dan-blanchard** [comment]
A separate Python interpreter runs each instance of each bolt and spout.  For more info, please see our documentation [parallelism and workers](http://streamparse.readthedocs.org/en/master/topologies.html#parallelism-and-workers)
