### ISSUE TITLE
Can't find 'streamparse.commands.run/-main'

### ISSUE THREAD

**Issue by Ulitochka** [Parsely/streamparse#210]
Thanks for your work.
Testing my topology via command: streamparse run -d
But I have exception: 
Can't find 'streamparse.commands.run/-main' as .class or .clj for lein run: please check the spelling.
java.io.FileNotFoundException: Could not locate streamparse/commands/run__init.class or streamparse/commands/run.clj on classpath.
But if I copy file project.clj from wordcount folder, it's work.

**Comment by dan-blanchard** [comment]
As you can see in the [quickstart docs](http://streamparse.readthedocs.org/en/master/quickstart.html), we recommend using the `sparse quickstart` command, which will give you a project that has all the necessary files in their correct places for everything to work.  A `project.clj` file is required with the currently released version of streamparse (although it might not be in future versions).
