### ISSUE TITLE
Replace "sparse run" with Flux YAML generator

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#213]
With @dan-blanchard's work on a Python Topology DSL, he is able to reproduce all of the streamparse commands in pure Python with the exception of `sparse run`.

This is because `sparse run` has some Clojure interop code that creates a Storm `LocalCluster` in memory, and invokes it using a `StormTopology` instance that is made by the Clojure DSL.

One approach is to take a closer look at Storm's new Flux contrib module. [As described here](https://github.com/apache/storm/tree/master/external/flux#yaml-configuration), Flux includes a YAML configuration, for which one option is to wire up a JVM class that returns a `StormTopology` instance. Alternatively we could generate the YAML for our topologies using the Python DSL representation of the Topology DAG.

This could be nice since Flux is bundled with Storm and so we could instruct people to install Storm locally (e.g. in an `/opt` directory) and then rely upon Flux and an auto-generated Flux YAML configuration (and perhaps a simple pre-compiled JAR that implements the Java class that Flux expects, depending on how this is implemented).

- multilang Flux YAML example: https://github.com/apache/storm/blob/master/external/flux/flux-examples/src/main/resources/multilang.yaml
- Flux CLI: https://github.com/apache/storm/tree/master/external/flux#command-line-options

Notice the flux `-l` and `-d` flags for local topology validation and running.

**Comment by dan-blanchard** [comment]
I'm included to just generate YAML from our DAG, because that would be very simple.
