### ISSUE TITLE
`sparse run` fails for projects with alphanumeric folder names

### ISSUE THREAD

**Issue by pramukta** [Parsely/streamparse#215]
(at least ones that start with numbers)

Hey, so found an annoying bug that might be an easy fix.  If I do the standard streamparse quickstart (ie something like `sparse quickstart test` followed by `cd test` and `sparse run`) everything is good.

However if I then `mv test 1test` then `cd 1test` and `sparse run`, it fails with buried `IOError` that is most relevant I think.

```
IOError: [Errno 2] No such file or directory: u'/private/var/folders/2x/gm9rwrz946g3svp3pq3jcr780000gn/T/4d425558-7987-45a3-a25f-5d2f8a563be9/supervisor/stormdist/wordcount-1-1451337589/resources/"/private/tmp/1test/logs"/streamparse_wordcount_count-bolt_3_27548.log'
```

The place in the code to start is probably around here, wherever it tries to setup logging:

```
  File "/.../python2.7/site-packages/streamparse/storm/component.py", line 246, in _setup_component
    backupCount=backup_count)
```

The issue looks like a quoting bug when building the path.  This was using `sparse 2.1.3` installed via pip on Mac OS 10.10.5.  The relevant spot seems to be gone from master, I'm guessing due to a move to pystorm so it might not be relevant to future versions but figured it could be worth reporting anyway.  Thanks for the help.

**Comment by dan-blanchard** [comment]
This is fixed in `master` and 3.0.0.dev0, so I'm going to close this.  (Note that `sparse run` is temporarily missing from the first 3.0 preview release and `master` though).
