### ISSUE TITLE
Spouts ack/fail methods are never called

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#216]
I was trying to ACK RabbitMQ messages after processing and found out that ack/fail spout's methods are never called. I needed this, because you can confirm message in RabbitMQ only from the same channel that send the message. Hence the ack method.

### How to reproduce:
1) use wordcount example

    sparse quickstart wordcount

2) modify WordSpout:

    class WordSpout(Spout):
    
        def initialize(self, stormconf, context):
            self.words = itertools.cycle(['dog', 'cat',
                                          'zebra', 'elephant'])
    
        def next_tuple(self):
            self.log("next tuple")
            word = next(self.words)
            self.emit([word])
    
        def ack(self, tup_id):
            self.log("acking")
    
        def fail(self, tup_id):
            self.log("failing")

3) modify WordCounter:

    class WordCounter(Bolt):
    
        auto_ack = False
        auto_fail = False
    
        def initialize(self, conf, ctx):
            self.counts = Counter()
    
        def process(self, tup):
            word = tup.values[0]
            self.counts[word] += 1
            self.emit([word, self.counts[word]])
            self.ack(tup)
            self.log('%s: %d' % (word, self.counts[word]))

You can use self.fail(tup) instead of self.ack()
There is no "acking" / "failing" output in log.

**Comment by dan-blanchard** [comment]
Which log are you looking in? `Component.log` [sends a log message to Storm](http://streamparse.readthedocs.org/en/v2.1.3/api.html#streamparse.storm.component.Component.log), which will be logged wherever your Storm logs end up.  It will not show up in the Python logs for your components.

**Comment by Darkless012** [comment]
Sorry about the confusion. The only logs I see are in log folder (plus the terminal output).
Are there any other places?
The self.log() from **next_tuple** method is logged and shown in terminal output. The self.log() from **ack** method is nowhere to find (even in log folder).

I've also tried to create file instead of logging (not sure where it ends), but without success. Anyway how can I confirm it further?

I need access to original channel (attribute of spout class) for the RabbitMQ to successfully ACK the message.

**Comment by Darkless012** [comment]
Ok. The problem was in Spout *next_tuple()*. You need to add tup_id to the emit.
And this ID is totally different from Tuple ID, which is generated by Apache Storm and in fact is called message_id in Apache Storm doc.

    class WordSpout(Spout):
        ...
        def next_tuple(self):
            self.log("next tuple")
            word = next(self.words)
            self.emit([word], tup_id=5)

I've added few information in DOC and made pull request. Can you please review it?
https://github.com/Parsely/streamparse/pull/217
