### ISSUE TITLE
`sparse visualize` command

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/streamparse#22]
Use an existing topology visualization tool like:

* [storm-spirit](https://github.com/hsestupin/storm-spirit)
* [StormSankey](https://github.com/cfergus/StormSankey)

or some mix of these, add a visualization command for topologies:

    sparse visualize [(--name | -n) <topology>] (--format | -f (png|jpg|gif)) output_filename

**Comment by amontalenti** [comment]
I'm actually thinking I may be able to implement `sparse visualize` on the Python side if #84 gets implemented, since in that case I'll have a DAG that I can actually visualize available to me in-memory in Python. (The Clojure dependency situation is a bit intractable if I want streamparse-jvm to maintain compatibility with Storm 0.8.2 through 0.9.3.) Linking here so I don't forget about it.

**Comment by dan-blanchard** [comment]
I think we might also be able to come up with a way to do this on the Python side just using the [REST API](https://github.com/apache/storm/blob/master/STORM-UI-REST-API.md).  Won't work <0.9.2, but I think that's probably okay, since #52 won't either.

**Comment by amontalenti** [comment]
Hmm, I think I like the idea of being able to visualize your topology *before* submitting it to Storm. I don't think it'd be too bad given that we already have a simple DAG model and plan to render to Clojure, so adding a renderer for Graphviz's digraph format would probably a piece of cake.

**Comment by dan-blanchard** [comment]
> I like the idea of being able to visualize your topology before submitting it to Storm

That's true; that would be nice.  

> adding a renderer for Graphviz's digraph format...

:+1: I like that idea.

**Comment by rduplain** [comment]
The current `sparse visualize` does not work.

**Comment by amontalenti** [comment]
@rduplain I wanted to mention that now that Topology DSL is coming, we can write this in pure Python. And further, that we have some prior art for this that may be easy to adapt, which is the dask visualizer. It's described briefly here:

http://dask.pydata.org/en/latest/inspect.html

**Comment by rduplain** [comment]
+1
