### ISSUE TITLE
Logging of modules inside my bolt

### ISSUE THREAD

**Issue by amitripshtos** [Parsely/streamparse#221]
Hey, first of all thank for for this great product!
I'm trying to use other python modules inside my bolt, but I did not figure out how and if it is possible to get the logs of the modules im using to be logged using "sparse run"

I think sparse run should include also loggings of modules inside the code.

**Comment by dan-blanchard** [comment]
If you want the logging to go to a separate file for each component, file the instructions in our docs [here](http://streamparse.readthedocs.io/en/stable/quickstart.html?highlight=logging#logging).  

If you want to log things to the Storm worker logs (only/strongly recommended if you're on Storm 1.0+), you just need to make sure your `config.json` does not set specify a log path. That will let you use the very nice Storm UI log search interface for your logs.

One tip is to try to always use `self.logger` for logging inside your bolt/spout.  

If you want logs for other modules to show up in your Storm logs, you must set their logging levels appropriately (e.g., `logging.getLogger('pykafka.broker').setLevel(logging.WARNING)`).  The root logger will be attached to the appropriate handler to send your logs either to separate files or the storm logs, but unless you set the logging level for your loggers, the messages won't go anyway.  The logging level in `config.json` just sets the level for your bolts and spouts' loggers, and the root logger's *handler* (but not the root logger itself).  This may change in the future as noted in #290.
