### ISSUE TITLE
ImportError: cannot import name yaml2

### ISSUE THREAD

**Issue by alfakini** [Parsely/streamparse#223]
While executing `sparse run -n test_topology` in the last version. It is actually an issue with [invoke](https://github.com/pyinvoke/invoke). I fixed the problem forcing `invoke==0.12.0` in my `requirements.txt`.

The issue there: https://github.com/pyinvoke/invoke/issues/319

**Comment by dan-blanchard** [comment]
This has been fixed in invoke, so I'm closing this.
