### ISSUE TITLE
Options parsing with '=' in the value

### ISSUE THREAD

**Issue by andrewkcarter** [Parsely/streamparse#225]
I'm running into difficulty when using options that contain an '=' character. This is the command I'm running after trying several quoting variations...
`sparse submit -n my-topology --option 'topology.worker.childopts="-Xmx256m -XX:PermSize=64m -XX:MaxPermSize=256m -Xms64m"'`

It looks like it's going into the lein command correctly but mangles it at perm size ...
<pre>
Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/my-topology.clj --host vagrant-ist-01 --port 6627 --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/tmp/virtualenvs/email-topology/bin/python"' --option 'streamparse.log.path="/var/log/storm"' --option 'streamparse.log.max_bytes=1000000' --option 'streamparse.log.backup_count=10' --option 'streamparse.log.level="info"' <b>--option topology.worker.childopts="-Xmx256m -XX:PermSize=64m -XX:MaxPermSize=256m -Xms64m"</b>
1744 [main] INFO  b.s.u.Utils - Using defaults.yaml from resources
{:option {<b>topology.worker.childopts -Xmx256m -XX:PermSize</b>, streamparse.log.level info, streamparse.log.backup_count 10, streamparse.log.max_bytes 1000000, streamparse.log.path /var/log/storm, topology.python.path /tmp/virtualenvs/my-topology/bin/python, topology.acker.executors 2, topology.workers 2}, :debug false, :port 6627, :host vagrant-ist-01, :help false}
2481 [main] INFO  b.s.u.Utils - Using defaults.yaml from resources
</pre>

And it shows up in storm as this:
<pre>topology.worker.childopts       "-Xmx256m -XX:PermSize"</pre>

**Comment by dan-blanchard** [comment]
As I've mentioned on other issues, we're moving away from using Clojure to pure Python + Thrift solution, so this will be closed when 3.0 is out.  There's a preview release available via PyPI (`pip install --pre streamparse==3.0.0.dev0`) if you want to try it out.

**Comment by dacohenii** [comment]
It looks like the issue in the `2.1.x` branch might be with the calls to `string/split` in `run.clj` and `submit_topology.clj` (in directory [streamparse/jvm/src/streamparse/commands/](https://github.com/Parsely/streamparse/tree/2.1.x/jvm/src/streamparse/commands)).

Here is the function in question:
```clojure
(defn -parse-topo-option [val-str]
  "Parse topology --option in option.key=val form."
  (let [[key val] (string/split val-str #"=")
       parsed-val (smart-read-str val)]
       {key parsed-val}))
```

Changing `(string/split val-str #"=")` to `(string/split val-str #"=" 2)` appears to fix the issue. (See [here](https://clojuredocs.org/clojure.string/split) for docs). 

I ran a couple of basic tests with the wordcount example, and the options appeared to be parsed correctly. Is there a way to add a test case for this? (I couldn't find one that made sense.)

Finally, I'm not especially familiar with Clojure, so I'm a little concerned of the possibility that this may cause something unrelated to break.
 
@dan-blanchard: Are there any issues with this change that jump out at you?

**Comment by dan-blanchard** [comment]
@dacohenii, that fix looks reasonable to me.  Since it's a one character change, I'd be willing to make it and push out a new snapshot of our Clojure library, which should get picked up by all 2.1.x users automatically.
