### ISSUE TITLE
"sparse list" crashed with Error

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#227]
command: "sparse list -e dev" crashes with:

Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer, compiling:(/tmp/form-init7673172597485779709.clj:1:72)

command "sparse stats -e dev" runs normally.
command "/opt/storm/bin/storm list" runs normally on nimbus.\

What other info is needed for debugging? Or how can I find out what is wrong? I'm not able to locate form-init7673172597485779709.clj file.

**Comment by dan-blanchard** [comment]
That's very strange.  In the near future we're going to put out streamparse 3.0 that won't actually use Clojure to communicate with Nimbus anymore, so this should be fixed by that.

**Comment by Darkless012** [comment]
I found out, that problem is with **storm-core** version. If I use 0.9.4, I can't deploy it to 0.10.0 version.
If I use 0.10.0, I can't list (sparse list) or kill (sparse kill) any topology. (The listing works with 0.9.4, even if the storm cluster is 0.10.0)

project.clj:

    (defproject lola "0.0.1-SNAPSHOT"
      :source-paths ["topologies"]
      :resource-paths ["_resources"]
      :target-path "_build"
      :min-lein-version "2.0.0"
      :jvm-opts ["-client"]
      :dependencies  [[org.apache.storm/storm-core "0.10.0"]
                      [com.parsely/streamparse "0.0.4-SNAPSHOT"]
                      ]
      :jar-exclusions     [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
      :uberjar-exclusions [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
      )

**Comment by dan-blanchard** [comment]
This is fixed in `master` and the 3.0.0.dev0 preview release, so I'm going to close this.
