### ISSUE TITLE
StreamParse and Apache Fink

### ISSUE THREAD

**Issue by chrismetcalf** [Parsely/streamparse#231]
It looks like Apache Fink [may be the successor to Storm](https://flink.apache.org/news/2015/12/11/storm-compatibility.html), so what does this mean for the future of StreamParse?

**Comment by amontalenti** [comment]
Don't think Flink is really the "successor" to Storm. In fact, Storm is actively developed with a new 1.0 release coming soon. See these slides for what's coming soon:

https://www.slideshare.net/mobile/ptgoetz/the-future-of-apache-storm

I think streamparse will likely stay focused on Storm support for time being.

**Comment by chrismetcalf** [comment]
:+1: Thanks @amontalenti, good to hear
