### ISSUE TITLE
Need DSL docs to explain how to use Streams properly

### ISSUE THREAD

**Issue by Darkless012** [Parsely/streamparse#252]
I'm trying to come to streamparse 3. And the most difficult part is Streams and Stream Grouping for inputs.

http://streamparse.readthedocs.io/en/master/topologies.html

There is only example of inputs with "A dict mapping from ComponentSpec to Grouping".
And outputs without streams.

So lets see API directly:
http://streamparse.readthedocs.io/en/master/api.html#streamparse.Bolt.spec

    inputs –
    Streams that feed into this Bolt.

    Two forms of this are acceptable:

    A dict mapping from ComponentSpec to Grouping.
    A list of Stream or ComponentSpec

Ok, so according to this the accepted inputs should be:

    inputs={my_bolt: Grouping.Grouping.fields('data')}
    or
    inputs=[my_bolt]
    
But what about streams?
Consider this example of outputs:

    outputs = [
            streamparse.Stream(fields=['data'],
                   name='unit',),
            streamparse.Stream(fields=['data'],
                   name='incident',),
        ]

So according to DOC inputs should be list of Streams?
    
    inputs=[streamparse.Stream(fields=['data'],
                   name='unit',)]

Throws an error: TypeError: Inputs must be ComponentSpec or GlobalStreamId objects.
So I guess it is not Stream that doc says, because there is no link to previous bolts (origination of data.)

So lets try:

    inputs={my_bolt : streamparse.Stream(fields=['data'],
                   name='unit',)}

KeyError: "Invalid stream for test_bolt: 'default'. Valid streams are: ['incident', 'unit']"
So I'm guessing the defaults is taken from here:
https://github.com/Parsely/streamparse/blob/master/streamparse/dsl/component.py#L80

So How do I make Simple case scenario with Streams and grouping?

    [first_spout]         [second_spout]
        \__________ __________/
                   |
           [process_bolt]
         __________|__________
        /                     \
    [unit_bolt]          [incident_bolt]
        \__________ __________/
                   |
              [save_bolt]

**Comment by dan-blanchard** [comment]
Thanks for the detailed write up! I can see this is one of those cases where the metaclass magic we're using to make things "simpler" for people can actually make things more confusing.

`outputs` can be a list of `Stream` objects, or a list of strings.  If it's a list of strings, those are the names of the fields for the `default` stream.

`inputs` can be a list of `Stream` objects, but these are not objects you build yourself, which could definitely use some clarification in the docs.  For what you want to do, the simplest thing would be:

```py
from streamparse import Bolt, Grouping, Spout, Stream, Topology


class FirstSpout(Spout):
    outputs = ['stuff']


class SecondSpout(Spout):
    outputs = ['other_stuff']


class ProcessBolt(Bolt):
    outputs = [Stream(fields=['data'], name='unit'),
               Stream(fields=['data'], name='incident')]


class UnitBolt(Bolt):
    outputs = ['unit_to_save']


class IncidentBolt(Bolt):
    outputs = ['incident_to_save']


class SaveBolt(Bolt):
    outputs = []


class ExampleTopology(Topology):
    first_spout = FirstSpout.spec()
    second_spout = SecondSpout.spec()
    process_bolt = ProcessBolt.spec(inputs=[first_spout, second_spout])
    unit_bolt = UnitBolt.spec(inputs=[process_bolt['unit']])
    incident_bolt = IncidentBolt.spec(inputs=[process_bolt['incident']])
    save_bolt = SaveBolt.spec(inputs=[unit_bolt, incident_bolt])
```

The key here is that to get a specific output `Stream` from a `ComponentSpec`, you just `__getitem__` via `spec['foo']`.

If you wanted to do a fields grouping with `unit_bolt` and `incident_bolt`, you could just do:

```py
    unit_bolt = UnitBolt.spec(inputs={process_bolt['unit']: Grouping.fields('data')})
    incident_bolt = IncidentBolt.spec(inputs={process_bolt['incident']: Grouping.fields('data')})
```

Hope that clears things up.

**Comment by Darkless012** [comment]
Wow. Thanks for the quick response and clarification.

**Comment by tdhopper** [comment]
@dan-blanchard: I can't find anything in the docs about how to properly use streams. (Been fighting with it for an hour until I found this.) Should I open an issue about having that added somewhere?

**Comment by dan-blanchard** [comment]
This issue is supposed to represent the fact that I need to add the comment about to our docs, so no need for another one.
