### ISSUE TITLE
Storm / Java / Clojure serialization-upon-submit problem (.ser files)

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#27]
When we issue `sparse submit` command, a local Clojure process runs that scripts the `StormSubmitter` class and talks to our remote nimbus host over an SSH tunnel.

This means that it's technically possible for the content submitted from the local machine to have been built by a Java/Clojure/Storm dependency version that *does not match* the one running on the server.

Normally, I'd think this doesn't matter -- after all, it's just a Thrift API, it should work as long as the bindings didn't change. The problem, however, is that the nimbus actually receives not just a built JAR with the topology submission, but also two serialized Java files, e.g. `stormcode.ser`. Because the serialization approach for these files is using plain old Java serialization, Storm nimbus/supervisor/workers will crash when trying to process these files if e.g. there is a Clojure version mismatch (as happened in the 0.9.1-incubating -> 0.9.2-incubating upgrade) or if any classes changed that might have updated their serialVersionId.

The way this exception looks in the case of a Clojure mismatch is as follows:

> java.lang.RuntimeException: java.io.InvalidClassException: clojure.lang.APersistentMap; local > class incompatible: stream classdesc serialVersionUID = 270281984708184947, local class > serialVersionUID = 8648225932767613808

I have a couple of ideas about how to fix this issue. One idea is to offer a way to "sync" your local repo to a remote Storm cluster by introspecting that Storm cluster to see what Storm version is running and rewriting the local project.clj file appropriately. Seems a little hacky.

The other way could be to change the way submission works altogether. Instead of using `StormSubmitter`, it could actually ssh into the nimbus machine and use `storm jar` using the storm CLI on that machine. Though this has the benefit of probably working with every version of Storm under the sun, it has more moving parts to worry about.

**Comment by dan-blanchard** [comment]
Now that we're using Thrift to talk to Nimbus in `sparse submit`, it would be very simple for us to just check the Storm version before running and update the `project.clj` as required.  I'd also like us to not require people to have a `project.clj` file at all and generate it on the fly, but that's a separate issue.  Users would still be able to specify one if they needed to customize the way Leiningen is going to compile their jar.

**Comment by dan-blanchard** [comment]
For some reason Nimbus doesn't appear to reliably return its version number, which is pretty irritating.

**Comment by dan-blanchard** [comment]
I am not seeing this issue anymore with the latest version of `storm submit`. The way we're doing this through Thrift now we actually do only send the JAR and a Thrift version of the topology to nimbus, and we do not create/send this extra file anymore.
