### ISSUE TITLE
Parallelism in Bolts

### ISSUE THREAD

**Issue by tanaysoni** [Parsely/streamparse#283]
I have a rather stupid Bolt which just sleeps for a second. Here's the code:

```
class TestBolt(Bolt):
    def process(self, tup):
        time.sleep(1)
```

In the clojure topology file, I played with different numbers for the parallelism of this Bolt, but still the throughput(number of acks) is limited to approximately 1/sec. This essentially means that there's no concurrency in the Bolt when executed on the Storm cluster.

What could I be missing here?

**Comment by amontalenti** [comment]
@tanaysoni Not sure what could be missing. How are you running your topology? When your topology is running, what do you see when you do `ps aux | grep 'streamparse'` or `ps aux | grep 'python'`? Do you actually have multiple Python processes starting up?

**Comment by tanaysoni** [comment]
@amontalenti Thanks for replying! I'm submitting topology on a local Storm cluster using `sparse submit`. I verified that Python multiple Python processing are running in accordance with the _parallelism hint_ given in the topology file.

**Comment by tdhopper** [comment]
@tanaysoni: Can you share more of your code (esp `clj` file)?

**Comment by tanaysoni** [comment]
@tdhopper 

Here's the topology definition:

```
(ns test_topology
  (:use     [streamparse.specs])
  (:gen-class))

(defn test_topology [options]
   [
    ;; spout configuration
    {"kafka-spout" (python-spout-spec
          options
          "spouts.kafka_spout.KafkaSpout"
          ["payload"]
          )
    }
    ;; bolt configuration
    {

    "router-bolt" (python-bolt-spec
          options
          {"kafka-spout" :shuffle}
          "bolts.test_bolts.Router"
          { "dummy" ["payload"]
          :p 2
          )

    "parallelism-test-bolt" (python-bolt-spec
          options
          {["router-bolt" "dummy"] ["payload"]}
          "bolts.fb_bolts.CommentBolt"
          ["payload"]
          :p 4
          )
    }
  ]
)
```
Things that I have verified:
1. The Spout is emitting at a reasonable high rate(none of the Bolts should be starved of tuples).
2. The `routing` Bolt in the topology is keeping up with the tuples emitted fromSpout. I verified this by the number of acknowledgments at this Bolt.
3. There are multiple Python processes spawing up for the `test` Bolt, the number exactly equal to the parallelism hint given in the topology file. The `test` Bolt sleeps for a second(as given in the code). Now, since multiple instance of this bolt are running, the throughput should be higher than 1/sec, but isn't the case here.

Please let me know if I can add any more information to help reproduce this.

**Comment by dan-blanchard** [comment]
Can you please try this with the latest version of streamparse? We no longer use the Clojure Topology DSL?

**Comment by tanaysoni** [comment]
Good news! This problem is solved with streamparse v. 3.0.1 and Storm v. 1.0.1. We can close this issue.
