### ISSUE TITLE
How do you pass an option to sparse run?

### ISSUE THREAD

**Issue by woisnow** [Parsely/streamparse#287]
I install storm 1.0.1 and streamparse 3.0 ok, but when i excute sparse run in wordcount , there an error ocur: 
Parsing file: /tmp/tmp8iTw5M.yaml
427  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
428  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
428  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
Exception in thread "main" java.lang.NoClassDefFoundError: backtype/storm/Config
	at org.apache.storm.flux.FluxBuilder.buildConfig(FluxBuilder.java:45)
	at org.apache.storm.flux.Flux.runCli(Flux.java:151)
	at org.apache.storm.flux.Flux.main(Flux.java:98)
Caused by: java.lang.ClassNotFoundException: backtype.storm.Config
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /root/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmp8iTw5M.yaml'

Aborting.

**Comment by woisnow** [comment]
I solved this problem, the reason is in project.clj, i changed all depency version to same as my env. Finally i run the WordCount smoothly, but i want to how can i change the storm.zookeper.port,
the default like this:
3319 [SyncThread:0] INFO  o.a.s.s.o.a.z.s.p.FileTxnLog - Creating new log file: log.1
3364 [SyncThread:0] INFO  o.a.s.s.o.a.z.s.ZooKeeperServer - Established session 0x15630ba32540000 with negotiated timeout 20000 for client /127.0.0.1:48549
3364 [main-SendThread(localhost:2000)] INFO  o.a.s.s.o.a.z.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2000, sessionid = 0x15630ba32540000, negotiated timeout = 20000
3364 [SyncThread:0] INFO  o.a.s.s.o.a.z.s.ZooKeeperServer - Established session 0x15630ba32540001 with negotiated timeout 20000 for client /127.0.0.1:48548
3364 [main-SendThread(localhost:2000)] INFO  o.a.s.s.o.a.z.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2000, sessionid = 0x15630ba32540001, negotiated timeout = 20000
3365 [SyncThread:0] INFO  o.a.s.s.o.a.z.s.ZooKeeperServer - Established session 0x15630ba32540002 with negotiated timeout 20000 for client /127.0.0.1:48550
3365 [main-SendThread(localhost:2000)] INFO  o.a.s.s.o.a.z.ClientCnxn - Session establishment complete on server localhost/127.0.0.1:2000, sessionid = 0x15630ba32540002, negotiated timeout = 20000
3368 [main-EventThread] INFO  o.a.s.s.o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
3368 [main-EventThread] INFO  o.a.s.s.o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
3368 [main-EventThread] INFO  o.a.s.s.o.a.c.f.s.ConnectionStateManager - State change: CONNECTED
3369 [main-EventThread] INFO  o.a.s.zookeeper - Zookeeper state update: :connected:none
3369 [main-EventThread] INFO  o.a.s.zookeeper - Zookeeper state update: :connected:none

**Comment by dan-blanchard** [comment]
With the final release of streamparse 3.0.0 that I just pushed out to PyPI, you have three options:

1.  Set the the options by creating a `config` attribute for your `Topology` that's a dict that makes from the setting you want to its value.  For example:

    ```py
    class SomeTopology(Topology):
        config = {'storm.zookeper.port': 1234}
    ``` 
2.  Pass the option via the command line:

    ```sh
    sparse run -n topology_name --option storm.zookeeper.port=1234
    ```

3.  Setting the option in your config.json:

    ```json
    {
        "topology_specs": "topologies/",
        "virtualenv_specs": "virtualenvs/",
        "envs": {
            "vagrant": {
                "user": "vagrant",
                "nimbus": "streamparse-box",
                "workers": [
                    "streamparse-box"
                ],
                "log": {
                    "level": "info"
                },
                "virtualenv_root": "/data/virtualenvs"
            },
            "options": {
                "storm.zookeeper.port": 1234
            }
        }
    }
    ```
