### ISSUE TITLE
sparse run with named streams not compatible with Storm 1.0.1

### ISSUE THREAD

**Issue by macheins** [Parsely/streamparse#291]
Hello,

the currently stable streamparse 3.0.0 is not compatible with Storm 1.0.1, which is the latest official release available on storm.apache.org. It requires at least Storm 1.0.2 or 1.1.0, because `FluxShellSpout.setNamedStream` and `FluxShellBolt.setNamedStream` are [only available since then](https://github.com/apache/storm/blob/v1.0.2/external/flux/flux-wrappers/src/main/java/org/apache/storm/flux/wrappers/bolts/FluxShellBolt.java#L100).

Since 1.0.2 and 1.1.0 are only [released on GitHub](https://github.com/apache/storm/releases/tag/v1.0.2) and not yet available on maven this might be a serious problem. Streamparse also uses 1.0.1 as a default in the examples.

**Comment by macheins** [comment]
It seems that named stream where not supported until now. So this might be no problem for existing topologies. Anyways it should be documented somewhere.

**Comment by dan-blanchard** [comment]
Sorry about that; we should probably have documented that better. I honestly thought 1.0.2 would be out officially by now.

**Comment by tdhopper** [comment]
I'm confused. Does that mean with 1.0.1 you can only use the default stream?

**Comment by amontalenti** [comment]
During local runs with `sparse run` due to a limitation in Flux, it seems.

**Comment by dan-blanchard** [comment]
With `sparse run`, yes. It was an oversight in Storm's Flux tool, which is what we now use to power `sparse run`, since we no longer have all that Clojure code in our codebase.  

`sparse submit` and everything works fine with 1.0.1.  And honestly, I hardly ever use `sparse run`.  I just fire up a Vagrant VM (like [this one](https://github.com/Parsely/streamparse/blob/master/examples/kafka-jvm/Vagrantfile)) and submit things to it for local testing.

**Comment by tdhopper** [comment]
👍 I don't use `run` either. Thanks.

**Comment by piyushchauhan2011** [comment]
Is it possible to install apache storm `1.0.2` or `1.1.0` version using source repository ? @dan-blanchard

**Comment by pythonishvili** [comment]
Hello, when going through the wordcount tutorial I am running into this problem: `Error: Could not find or load main class org.apache.storm.flux.Flux`. Is this related? How can I fix it. I'm new to streamparse and well, not familiar with Java ecosystem at all. Thanks

**Comment by piyushchauhan2011** [comment]
Apache Storm `1.0.2` is out on `maven` try (yay) @pythonishvili should work with that.

**Comment by pythonishvili** [comment]
Thanks, my problem and solution were already covered here https://github.com/Parsely/streamparse/issues/297

**Comment by piyushchauhan2011** [comment]
Still getting the error message when running `sparse run`

```
Error: Could not find or load main class org.apache.storm.flux.Flux

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /home/ec2-user/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmpmzJyXt.yaml'
```

Anything that can be done to sort it out ? @dan-blanchard 

With `spark submit` I'm getting this error

```
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==3.0.1', 'console_scripts', 'sparse')()
  File "/usr/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/streamparse/cli/submit.py", line 244, in main
    override_name=args.override_name)
  File "/usr/local/lib/python2.7/site-packages/streamparse/cli/submit.py", line 169, in submit_topology
    override_name=override_name)
  File "/usr/local/lib/python2.7/site-packages/streamparse/cli/update_virtualenv.py", line 84, in create_or_update_virtualenvs
    hosts=env.storm_workers)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/fabric/decorators.py", line 180, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/streamparse/cli/update_virtualenv.py", line 26, in _create_or_update_virtualenv
    virtualenv_path = '/'.join((virtualenv_root, virtualenv_name))
TypeError: sequence item 0: expected string or Unicode, NoneType found
```

**Comment by piyushchauhan2011** [comment]
With `python3`:

```
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==3.0.1', 'console_scripts', 'sparse')()
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/submit.py", line 244, in main
    override_name=args.override_name)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/submit.py", line 169, in submit_topology
    override_name=override_name)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/update_virtualenv.py", line 84, in create_or_update_virtualenvs
    hosts=env.storm_workers)
  File "/usr/local/lib64/python3.4/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib64/python3.4/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib64/python3.4/site-packages/fabric/decorators.py", line 180, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/update_virtualenv.py", line 26, in _create_or_update_virtualenv
    virtualenv_path = '/'.join((virtualenv_root, virtualenv_name))
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by tanaysoni** [comment]
@piyushchauhan2011 Have you ensured the virtualenv requirements file has the correct version of `streamparse`? Can you add your requirements file, `config.json`, and `project.clj` here?

**Comment by piyushchauhan2011** [comment]
`pip list` gives

```
ecdsa (0.13)
Fabric3 (1.12.post1)
Jinja2 (2.8)
MarkupSafe (0.23)
msgpack-python (0.4.8)
paramiko (1.17.2)
pip (8.1.2)
ply (3.8)
prettytable (0.7.2)
pycrypto (2.6.1)
pystorm (3.0.1)
requests (2.11.0)
ruamel.yaml (0.11.15)
setuptools (12.2)
simplejson (3.8.2)
six (1.10.0)
streamparse (3.0.1)
thriftpy (0.3.8)
```

`config.json` is:
```
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "",
            "ssh_password": "",
            "nimbus": "",
            "workers": [],
            "log": {
                "path": "",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "virtualenv_root": ""
        }
    }
}
```

and `project.clj` is:

```
(defproject wordcount "0.0.1-SNAPSHOT"
  :resource-paths ["_resources"]
  :target-path "_build"
  :min-lein-version "2.0.0"
  :jvm-opts ["-client"]
  :dependencies  [[org.apache.storm/storm-core "1.0.2"]
                  [org.apache.storm/flux-core "1.0.2"]]
  :jar-exclusions     [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  :uberjar-exclusions [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
  )
```

@tanaysoni

**Comment by tanaysoni** [comment]
You need to remove `#"org.apache.storm"` from jar-exclustions and `uberjar-exclusions`

**Comment by macheins** [comment]
Since 1.0.2 is out now I suggest to fix the examples / `quickstart` to use the latest Storm version in the next patch version of streamparse.

**Comment by piyushchauhan2011** [comment]
Yeah works like charm @tanaysoni . I also suggest they fix this error too in next version when I run `sparse submit`

```
Traceback (most recent call last):
  File "/usr/local/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==3.0.1', 'console_scripts', 'sparse')()
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/sparse.py", line 56, in main
    args.func(args)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/submit.py", line 244, in main
    override_name=args.override_name)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/submit.py", line 169, in submit_topology
    override_name=override_name)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/update_virtualenv.py", line 84, in create_or_update_virtualenvs
    hosts=env.storm_workers)
  File "/usr/local/lib64/python3.4/site-packages/fabric/tasks.py", line 425, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/usr/local/lib64/python3.4/site-packages/fabric/tasks.py", line 172, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/lib64/python3.4/site-packages/fabric/decorators.py", line 180, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/streamparse/cli/update_virtualenv.py", line 26, in _create_or_update_virtualenv
    virtualenv_path = '/'.join((virtualenv_root, virtualenv_name))
TypeError: sequence item 0: expected str instance, NoneType found
```

@macheins

**Comment by amontalenti** [comment]
Yes, now that Storm 1.0.2 is officially released, @dan-blanchard will make a patch release of streamparse and we'll also run through all the quickstart/examples to make sure things are working well again. Thanks, @piyushchauhan2011 & @macheins.p

**Comment by dan-blanchard** [comment]
@piyushchauhan2011 The error you're seeing is because you don't have your `virtualenv_root` set to anything, so it doesn't know where to create the virtualenv.  We really could use some config validation, which is an open issue #173.

**Comment by piyushchauhan2011** [comment]
Cool @dan-blanchard  After reading the `config.json` structure, now I understand and believe it works correctly.

**Comment by piyushchauhan2011** [comment]
Also if anybody else is struggling with `spark submit`, I was able to resolve with this config file. Make sure to configure the `~/.ssh/config` file too which is listed below to allow `ssh` locally to same system. I'm using AWS to included my `*.pem` file and provided the path for it `~/.ssh/config`.

`config.json`
```
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "ec2-user",
            "ssh_password": "",
            "nimbus": "localhost",
            "workers": [
       		"localhost"
       	    ],
            "log": {
                "path": "",
                "max_bytes": 1000000,
                "backup_count": 10,
                "level": "info"
            },
            "virtualenv_root": "/home/ec2-user/stormenv"
        }
    }
}
```

Here is `~/.ssh/config`:
```
Host localhost
    HostName localhost
    Port 22
    User ec2-user
    IdentityFile ~/.ssh/*.pem
```

Not a production config but as a uni-grad, helps to see something 😄 

![screen shot 2016-08-13 at 3 34 09 am](https://cloud.githubusercontent.com/assets/693487/17631419/5ead81d6-6107-11e6-9869-413d76c6177f.png)

**Comment by dan-blanchard** [comment]
Storm 1.0.2 is out and I've just updated our `project.clj` exclusions to not exclude flux (738c058), so we'll be good with the next release.
