### ISSUE TITLE
could not find or load main class org.apache.storm.flux.Flux

### ISSUE THREAD

**Issue by Zdenlak** [Parsely/streamparse#295]
I am using streamparse version 3.0.1 and storm version is 1.0.1. The Java RunTime and Leiningen are 1.8.0_25-b17 and 2.6.1 respectively. When I am trying to run wordcount example with command 'sparse run', it told me 'Could not find or load main class org.apache.storm.flux.Flux'. Below is the message:

[MESSAGE START]
➜  wordcount sparse run

Cleaning from prior builds...
Creating topology Uber-JAR...
Uber-JAR created: /Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar
Removing _resources temporary directory...done
[localhost] local: storm jar /Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /var/folders/hp/khcf_qw119z25wc65qfr976m0000gn/T/tmpSgczNF.yaml
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/usr/local/Cellar/storm/1.0.1/libexec -Dstorm.log.dir=/usr/local/Cellar/storm/1.0.1/libexec/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /usr/local/Cellar/storm/1.0.1/libexec/lib/asm-5.0.3.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/clojure-1.7.0.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/disruptor-3.3.2.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/kryo-3.0.3.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-api-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-core-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-over-slf4j-1.6.6.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/log4j-slf4j-impl-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/minlog-1.3.0.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/objenesis-2.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/reflectasm-1.10.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/servlet-api-2.5.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/slf4j-api-1.7.7.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/storm-core-1.0.1.jar:/usr/local/Cellar/storm/1.0.1/libexec/lib/storm-rename-hack-1.0.1.jar:/Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar:/usr/local/Cellar/storm/1.0.1/libexec/conf:/usr/local/Cellar/storm/1.0.1/libexec/bin -Dstorm.jar=/Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /var/folders/hp/khcf_qw119z25wc65qfr976m0000gn/T/tmpSgczNF.yaml
Error: Could not found or load main class org.apache.storm.flux.Flux

Fatal error: local() encountered an error (return code 1) while executing 'storm jar /Users/Thomas/Apps/PlayGround/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /var/folders/hp/khcf_qw119z25wc65qfr976m0000gn/T/tmpSgczNF.yaml'

Aborting.
[MESSAGE END]

I followed the instructions here to solve, but it doesn't work.  [http://search-hadoop.com/m/8gnYyJOm2jNEbR62&subj=Re+Error+Could+not+find+or+load+main+class+org+apache+storm+flux+Flux?q=Flux]

Can anyone help me, thank you very much.

**Comment by tanaysoni** [comment]
@Zdenlak: Could you please share your `project.clj` file?

**Comment by Zdenlak** [comment]
OK, below is my project.clj, thank you

[project.clj.txt](https://github.com/Parsely/streamparse/files/393200/project.clj.txt)

[project.clj content]

(defproject wordcount "0.0.1-SNAPSHOT"
    :resource-paths ["_resources"]
    :target-path "_build"
    :min-lein-version "2.0.0"
    :jvm-opts ["-client"]
    :dependencies  [[org.apache.storm/storm-core "1.0.1"]
                                [org.apache.storm/flux-core "1.0.1"]]
    :jar-exclusions     [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF"     #"meta-inf" #"\.yaml"]
    :uberjar-exclusions [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF"     #"meta-inf" #"\.yaml"]
    )

**Comment by tanaysoni** [comment]
@Zdenlak Could you try removing `#"org.apache.storm"` from jar-exclusions & uberjar-exclustions ?

**Comment by Zdenlak** [comment]
It worked. Thank you very much.

**Comment by dan-blanchard** [comment]
I put something about this in `sparse run --help`, but we could probably use some better error handling around this.

**Comment by amontalenti** [comment]
@tanaysoni Good call on the exclusions in project.clj. Since `project.clj` is probably never going away for `streamparse` (given how convenient it is for Java packaging), we could probably use better docs on how it works. Contributions welcome on this :)

**Comment by tanaysoni** [comment]
@amontalenti Having struggled myself here, I certainly see immense value of documentation on this. I'll have to get more understanding of how `project.clj` is being used, before I may write documentation. I'll give it a shot sometime soon.

**Comment by JohanHolman** [comment]
Thank you, this was the answer I was looking for!

**Comment by dan-blanchard** [comment]
```
$ sparse run --help
usage: sparse run [-h] [-a OPTIONS] [-d [OPTIONS]] [-e ENVIRONMENT] [-n NAME]
                  [-o OPTIONS] [-t TIME] [-w OPTIONS]

Run a local Storm topology.

Note: If you have "org.apache.storm" in your uberjar-exclusions list in your
project.clj, this will fail. Temporarily remove it to use `sparse run`.
```

**Comment by trebsirk** [comment]
thank you. this worked for me.
