### ISSUE TITLE
shuffle grouping with v. 3.0.1

### ISSUE THREAD

**Issue by tanaysoni** [Parsely/streamparse#296]
I see in the documentation that default grouping is `shuffle`, but how to explicitly declare in topology? 

This works for fields grouping: 
`test_bolt = TestBolt.spec(inputs={router_bolt: Grouping.fields('payloads')},  par=2)`

But, the `Grouping` object has no attribute `shuffle`.

**Comment by amontalenti** [comment]
The default is `Grouping.SHUFFLE`, as covered in the docs here:

http://streamparse.readthedocs.io/en/stable/api.html#streamparse.Grouping
