### ISSUE TITLE
sparse run on wordcount quickstart failed due to flux

### ISSUE THREAD

**Issue by fardhana** [Parsely/streamparse#297]
Hi, since i upgrade to streamparse 3.0.1
My topology stop running, event the quickstart is not working due to flux error
I already follow every step in this page: http://streamparse.readthedocs.io/en/stable/quickstart.html

> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$
> 
>  sparse quickstart wordcount
> 
> Creating your wordcount streamparse project...
>     create    wordcount
>     create    wordcount/.gitignore
>     create    wordcount/config.json
>     create    wordcount/fabfile.py
>     create    wordcount/project.clj
>     create    wordcount/README.md
>     create    wordcount/src
>     create    wordcount/src/bolts
>     create    wordcount/src/bolts/__init__.py
>     create    wordcount/src/bolts/wordcount.py
>     create    wordcount/src/spouts
>     create    wordcount/src/spouts/__init__.py
>     create    wordcount/src/spouts/words.py
>     create    wordcount/topologies
>     create    wordcount/topologies/wordcount.py
>     create    wordcount/virtualenvs
>     create    wordcount/virtualenvs/wordcount.txt
> Done.
> 
> Try running your topology locally with:
> 
> 	cd wordcount
> 	sparse run
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$ cd wordcount/c
> -bash: cd: wordcount/c: No such file or directory
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$ cd wordcount/
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount/wordcount$ vim README.md 
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount/wordcount$ sparse run
> Cleaning from prior builds...
> Creating topology Uber-JAR...
> Uber-JAR created: /vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar
> Removing _resources temporary directory...done
> [localhost] local: storm jar /vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmplPvS8S.yaml
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
> Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/vagrant/resources/apache-storm-1.0.1 -Dstorm.log.dir=/home/vagrant/resources/apache-storm-1.0.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /home/vagrant/resources/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/objenesis-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/asm-5.0.3.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar:/home/vagrant/resources/apache-storm-1.0.1/conf:/home/vagrant/resources/apache-storm-1.0.1/bin -Dstorm.jar=/vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmplPvS8S.yaml
> Error: Could not find or load main class org.apache.storm.flux.Flux
> 
> Fatal error: local() encountered an error (return code 1) while executing 'storm jar /vagrant/streamparse-master/examples/wordcount/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmplPvS8S.yaml'
> 
> Aborting.
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount/wordcount$ storm version
> Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/vagrant/resources/apache-storm-1.0.1 -Dstorm.log.dir=/home/vagrant/resources/apache-storm-1.0.1/logs -Djava.library.path=/usr/local/lib:/opt/local/lib:/usr/lib -Dstorm.conf.file= -cp /home/vagrant/resources/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/objenesis-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/asm-5.0.3.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/home/vagrant/resources/apache-storm-1.0.1/conf org.apache.storm.utils.VersionInfo
> Storm 1.0.1
> URL https://git-wip-us.apache.org/repos/asf/storm.git -r b5c16f919ad4099e6fb25f1095c9af8b64ac9f91
> Branch (no branch)
> Compiled by tgoetz on 2016-04-29T20:44Z
> From source with checksum 1aea9df01b9181773125826339b9587e
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount/wordcount$ sparse --version
> sparse 3.0.1
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount/wordcount$

**Comment by amontalenti** [comment]
@dan-blanchard I only just noticed that this issue is affecting all new users following the quickstart guide, because the exclusions for `org.apache.storm` are in the `project.clj` bootstrap file:

https://github.com/Parsely/streamparse/blob/master/streamparse/bootstrap/project/project.jinja2.clj#L8-L9

Think we should figure out a workaround. I am sure there is a way to exclude every `org.apache.storm` package except for `org.apache.storm.flux` from the JAR.

**Comment by dan-blanchard** [comment]
Other than enumerating them all, I couldn't think of one, but yeah, this is obviously a constant issue.

**Comment by dan-blanchard** [comment]
@fardhana If you follow the instructions in `sparse run --help` about modifying your `project.clj`, you'll be good to go for now.

**Comment by fardhana** [comment]
@dan-blanchard i've follow the instruction, but the error is still occurred.
This is the output:

> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$ sparse run
> Cleaning from prior builds...
> Creating topology Uber-JAR...
> Uber-JAR created: /vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar
> Removing _resources temporary directory...done
> [localhost] local: storm jar /vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmp2ijCpd.yaml
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.apache.storm.config$read_storm_config.invoke(config.clj:78)
> 	at org.apache.storm.config$fn__973.invoke(config.clj:100)
> 	at org.apache.storm.config__init.load(Unknown Source)
> 	at org.apache.storm.config__init.<clinit>(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:278)
> 	at clojure.lang.RT.classForName(RT.java:2154)
> 	at clojure.lang.RT.classForName(RT.java:2163)
> 	at clojure.lang.RT.loadClassForName(RT.java:2182)
> 	at clojure.lang.RT.load(RT.java:436)
> 	at clojure.lang.RT.load(RT.java:412)
> 	at clojure.core$load$fn__5448.invoke(core.clj:5866)
> 	at clojure.core$load.doInvoke(core.clj:5865)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.core$load_one.invoke(core.clj:5671)
> 	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
> 	at clojure.core$load_lib.doInvoke(core.clj:5710)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:142)
> 	at clojure.core$apply.invoke(core.clj:632)
> 	at clojure.core$load_libs.doInvoke(core.clj:5753)
> 	at clojure.lang.RestFn.applyTo(RestFn.java:137)
> 	at clojure.core$apply.invoke(core.clj:634)
> 	at clojure.core$use.doInvoke(core.clj:5843)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at org.apache.storm.command.config_value$loading__5340__auto____11251.invoke(config_value.clj:16)
> 	at org.apache.storm.command.config_value__init.load(Unknown Source)
> 	at org.apache.storm.command.config_value__init.<clinit>(Unknown Source)
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:278)
> 	at clojure.lang.RT.classForName(RT.java:2154)
> 	at clojure.lang.RT.classForName(RT.java:2163)
> 	at clojure.lang.RT.loadClassForName(RT.java:2182)
> 	at clojure.lang.RT.load(RT.java:436)
> 	at clojure.lang.RT.load(RT.java:412)
> 	at clojure.core$load$fn__5448.invoke(core.clj:5866)
> 	at clojure.core$load.doInvoke(core.clj:5865)
> 	at clojure.lang.RestFn.invoke(RestFn.java:408)
> 	at clojure.lang.Var.invoke(Var.java:379)
> 	at org.apache.storm.command.config_value.<clinit>(Unknown Source)
> Caused by: java.lang.RuntimeException: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar!/defaults.yaml, jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/defaults.yaml]
> 	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:307)
> 	at org.apache.storm.utils.Utils.readDefaultConfig(Utils.java:351)
> 	at org.apache.storm.utils.Utils.readStormConfig(Utils.java:387)
> 	at org.apache.storm.utils.Utils.<clinit>(Utils.java:119)
> 	... 39 more
> Caused by: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar!/defaults.yaml, jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/defaults.yaml]
> 	at org.apache.storm.utils.Utils.getConfigFileInputStream(Utils.java:333)
> 	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:287)
> 	... 42 more
> Running: java -client -Ddaemon.name= -Dstorm.options= -Dstorm.home=/home/vagrant/resources/apache-storm-1.0.1 -Dstorm.log.dir=/home/vagrant/resources/apache-storm-1.0.1/logs -Djava.library.path= -Dstorm.conf.file= -cp /home/vagrant/resources/apache-storm-1.0.1/lib/servlet-api-2.5.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-over-slf4j-1.6.6.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/objenesis-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-rename-hack-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/minlog-1.3.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-core-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/reflectasm-1.10.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-api-2.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/slf4j-api-1.7.7.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/disruptor-3.3.2.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/asm-5.0.3.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/clojure-1.7.0.jar:/home/vagrant/resources/apache-storm-1.0.1/lib/kryo-3.0.3.jar:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar:/home/vagrant/resources/apache-storm-1.0.1/conf:/home/vagrant/resources/apache-storm-1.0.1/bin -Dstorm.jar=/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmp2ijCpd.yaml
> SLF4J: Class path contains multiple SLF4J bindings.
> SLF4J: Found binding in [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/log4j-slf4j-impl-2.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: Found binding in [jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/org/slf4j/impl/StaticLoggerBinder.class]
> SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
> SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
> Parsing file: /tmp/tmp2ijCpd.yaml
> 658  [main] INFO  o.a.s.f.p.FluxParser - loading YAML from input stream...
> 660  [main] INFO  o.a.s.f.p.FluxParser - Not performing property substitution.
> 661  [main] INFO  o.a.s.f.p.FluxParser - Not performing environment variable substitution.
> 751  [main] INFO  o.a.s.f.FluxBuilder - Detected DSL topology...
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.apache.storm.topology.BaseConfigurationDeclarer.<init>(BaseConfigurationDeclarer.java:26)
> 	at org.apache.storm.topology.TopologyBuilder$ConfigGetter.<init>(TopologyBuilder.java:454)
> 	at org.apache.storm.topology.TopologyBuilder$SpoutGetter.<init>(TopologyBuilder.java:471)
> 	at org.apache.storm.topology.TopologyBuilder.setSpout(TopologyBuilder.java:343)
> 	at org.apache.storm.flux.FluxBuilder.buildSpouts(FluxBuilder.java:353)
> 	at org.apache.storm.flux.FluxBuilder.buildTopology(FluxBuilder.java:84)
> 	at org.apache.storm.flux.Flux.runCli(Flux.java:153)
> 	at org.apache.storm.flux.Flux.main(Flux.java:98)
> Caused by: java.lang.RuntimeException: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar!/defaults.yaml, jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/defaults.yaml]
> 	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:307)
> 	at org.apache.storm.utils.Utils.readDefaultConfig(Utils.java:351)
> 	at org.apache.storm.utils.Utils.readStormConfig(Utils.java:387)
> 	at org.apache.storm.utils.Utils.<clinit>(Utils.java:119)
> 	... 8 more
> Caused by: java.io.IOException: Found multiple defaults.yaml resources. You're probably bundling the Storm jars with your topology jar. [jar:file:/home/vagrant/resources/apache-storm-1.0.1/lib/storm-core-1.0.1.jar!/defaults.yaml, jar:file:/vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar!/defaults.yaml]
> 	at org.apache.storm.utils.Utils.getConfigFileInputStream(Utils.java:333)
> 	at org.apache.storm.utils.Utils.findAndReadConfigFile(Utils.java:287)
> 	... 11 more
> 
> Fatal error: local() encountered an error (return code 1) while executing 'storm jar /vagrant/streamparse-master/examples/wordcount/_build/wordcount-0.0.1-SNAPSHOT-standalone.jar org.apache.storm.flux.Flux --local --no-splash --sleep 9223372036854775807 /tmp/tmp2ijCpd.yaml'
> 
> Aborting.
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$ cat project.clj 
> (defproject wordcount "0.0.1-SNAPSHOT"
>   :resource-paths ["_resources"]
>   :target-path "_build"
>   :min-lein-version "2.0.0"
>   :jvm-opts ["-client"]
>   :dependencies  [[org.apache.storm/storm-core "1.0.1"]
>                   [org.apache.storm/flux-core "1.0.1"]]
>   :jar-exclusions     [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
>   )
> (env)vagrant@devmachine:/vagrant/streamparse-master/examples/wordcount$

**Comment by dan-blanchard** [comment]
Looks like you have multiple `defaults.yaml` files.  We don't generate those with streamparse as far as I'm aware, so I'm not sure what would cause that.

**Comment by amontalenti** [comment]
I actually think he deleted his `:uberjar-exclusions` line altogether, which got rid of the exclusion for `.yaml` files that is at the end there.

@fardhana This is probably how you want your project.clj file to look for `sparse run` to work:

https://gist.github.com/amontalenti/a6be425a8b8c9455a716b189c7a71511

**Comment by fardhana** [comment]
Yes, your comment is right @amontalenti 
My quickstart is successfully run in my local now. Thanks @dan-blanchard as well
