### ISSUE TITLE
Number of acker executors does not default to the number of worker nodes

### ISSUE THREAD

**Issue by macheins** [Parsely/streamparse#298]
Hello,

if the `-w` option of `sparse submit` is set to some number `N` the number of acker executors is said to be set to `N` as well. But after setting `-w` on `sparse submit` and not setting `-a` I observed that no ackers are spawned and only unreliable emits are used. After setting `-a` in addition to `-w` the ackers are spawned and emits become reliable.

So I think the default value for `-a` is not correctly set to the number of workers by default.

**Comment by macheins** [comment]
Can anyone confirm the issue? I think its serious, because if people trust the docs and only set `-w` they always get an unreliable topology and hard to track problems.

**Comment by dan-blanchard** [comment]
Sorry @macheins, I could have sworn I replied to this before.  I must just never have hit the "Comment" button.

> if the -w option of sparse submit is set to some number N the number of acker executors is said to be set to N as well.

That is not actually how things are supposed to work.  If there is something in the docs that makes that confusing, please point it out.  `-w` and `-a` are entirely independent settings as of streamparse 3.0.0.  Previously there was a `--par` option that set them both, but we dropped that.  

Both `-w` and `-a` default to the number of worker nodes for your environment listed in your `config.json`.  For most people, that is the recommended setting, so people will rarely have to change either of these.
