### ISSUE TITLE
Local Storm Version Problem. Running streamparse on Hortonworks storm.

### ISSUE THREAD

**Issue by pavanpolineni** [Parsely/streamparse#303]
Hi all,

I am facing Local Storm Version Problem. I am running streamparse==3.0.1 on hortonworks Storm platform (0.10.0.2.4.2.0). 

> sparse run
> Traceback (most recent call last):
>   File "/usr/local/bin/sparse", line 9, in <module>
>     load_entry_point('streamparse==3.0.1', 'console_scripts', 'sparse')()
>   File "/usr/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 56, in main
>     args.func(args)
>   File "/usr/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 84, in main
>     run_local_topology(name=args.name, time=args.time, options=args.options)
>   File "/usr/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 41, in run_local_topology
>     'match.'.format(local_version, project_version))
> **ValueError: Local Storm version, 0.10.0.2.4.2.0, is not the same as the version in your project.clj, 1.0.1. The versions must match.**

My Project.clj file is below.

> (defproject wordcount "0.0.1-SNAPSHOT"
>   :resource-paths ["_resources"]
>   :target-path "_build"
>   :min-lein-version "2.0.0"
>   :jvm-opts ["-client"]
>   :dependencies  [[org.apache.storm/storm-core "0.10.0"]
>                   [org.apache.storm/flux-core "1.0.1"]]
>   :jar-exclusions     [#"log4j\.properties" #"org.apache.storm" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
>   :uberjar-exclusions [#"log4j\.properties" #"backtype" #"trident" #"META-INF" #"meta-inf" #"\.yaml"]
>   )

I tried by removing #"org.apache.storm" in both jar and uberjar-exclusions. But Luck. **I know we need to change in project.clj. but what is the line we need to change to get the storm from Horton works.
so that streamparse and hortonworks work together.**

**Comment by HeartSaVioR** [comment]
You need to set the version of storm-core and flux-core to `0.10.0.2.4.2.0`since Hortonworks Storm packages its own version. Moreover, Storm 1.0.0 is not backward compatible with 0.10.0.
You might also need to add Hortonworks repository for pulling dependencies.

**Comment by dan-blanchard** [comment]
@pavanpolineni, you need to follow the [instructions in our docs](http://streamparse.readthedocs.io/en/stable/quickstart.html#using-unofficial-versions-of-storm) for how to setup your `project.clj` file for using a Hortonworks Storm release.  Although Storm 1.0 is not backward compatible with 0.10.0, streamparse is compatible with 0.9 and above.
