### ISSUE TITLE
Development environment support question

### ISSUE THREAD

**Issue by goldiiman** [Parsely/streamparse#319]
hi

I use PyCharm and coming from a Jetbrains tools background I use IntelliSense to pick up new code packages and projects.

I understand streamparase has an immense of pre-execute JAR work that it performs, so as much as I would love to have a breakpoint.. I do not expect there is a way.. is there? I use debug by log output which is painful.

In order to get some code IntelliSense I have to map the sparse directory as well the development environment.

is there a better solution to get as much development support in code checking IntelliSense

try:
    from spouts.Foo import Foo
except:
    from src.spouts.Foo import Foo

should this question really goto the Google groups?

thanks
Martin

**Comment by Darkless012** [comment]
I'm not entirely sure about your question. But In PyCharm you can set some folder in project as "source root" (Right click on the "src" dir -> Mark Directory as -> Sources Root)

Is this it? If not can you reformulate the question please?

**Comment by dan-blanchard** [comment]
Closing because of lack of response.
