### ISSUE TITLE
csv-table error in docs

### ISSUE THREAD

**Issue by tdhopper** [Parsely/streamparse#321]
http://streamparse.readthedocs.io/en/v3.1.1/quickstart.html#project-structure is missing the table that should follow. It's present in the [raw RST](https://github.com/Parsely/streamparse/blob/b51419d9d942a45b4554b44e924b128410fb0a84/doc/source/quickstart.rst).

**Comment by tdhopper** [comment]
It looks like it's present in the 2.* docs, but not the 3.* docs. No idea why.

**Comment by tdhopper** [comment]
6e5997abe0295019f77d2e37d32e553df630d535 seems to have fixed it. Thanks, Dan.

**Comment by tdhopper** [comment]
Maybe it's still updating, but it looks like http://streamparse.readthedocs.io/en/v3.1.1/quickstart.html isn't actually fixed.

**Comment by dan-blanchard** [comment]
Yeah, I was playing around. The last commit should fix it, because I switched away from `csv-table`
