### ISSUE TITLE
How to Change Topology Assigned Mem

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#323]
submitting a topology with defaults, the UI shows the value of 832MB in topology summary
i couldn't find where it is set, or which config option is used for this
how can i increase this value? can this value up to total worker machine memory?

**Comment by Darkless012** [comment]
You can set any Apache Storm option (topology-wide) in config.json

    "envs": {
        ...
        "dev": {
            ...
            "options": {
                "worker.heap.memory.mb": 1024
            }
        }
    }

You will need to check Apache Storm configuration guide for the values needed.

**Comment by mbande** [comment]
thank you @Darkless012

**Comment by mbande** [comment]
i increased that option to 30000 (~30GB), but the storm UI shows 1088MB
however it is increased, it's not increased as it should
what's happening here?
