### ISSUE TITLE
sparse submit takes too long

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#324]
i've created a project that has a simple topology (1 spout, 4 simple bolts, but there is other codes to import!)
trying to submit the topology to a local nimbus, it takes too long to finish (~15 minutes)
the steps `Cleaning from prior builds...` and`Creating topology JAR...``` are the biggest problem
i wonder why this two steps should take too long, specially the cleaning phase
i am using streamparse 3.1.1 with storm 1.0.2 on java 8 and python 3.

**Comment by mbande** [comment]
found the root cause,
as i run the command as root user, ```lein``` complains about running as super user and wait's for user input, but the sparse just prints ```leaning from prior builds...``` and waits for user input!

**Comment by Darkless012** [comment]
Why do you run lein as superuser (I mean is there a valid reason to)?

If so, it needs to be solved. Otherwise I would stick to lein and don't run as root.

**Comment by mbande** [comment]
i know this is not good to run lein as root, i just faced and reported the issue

**Comment by Darkless012** [comment]
Some project https://github.com/framework-one/cfmljure/issues/12 also checks for root user and abort running.

This is the lein code responsible https://github.com/technomancy/leiningen/blob/c06bc76959ab3377fab4865f6acce1e08bd8fdbc/bin/lein#L86-L103

Any ideas how to deal with this?
