### ISSUE TITLE
logger is logging wrong component name!

### ISSUE THREAD

**Issue by mbande** [Parsely/streamparse#338]
in a topology containing ```foo``` and ```bar``` components, ```sparse run``` is logging lines like this:
```3266 [Thread-24-foo-executor[6 6]] INFO  bar - 2016-11-17 14:48:59,020 INFO some message```
```foo``` logging as other component!
changing the log message to ```self.component_name``` in component code:
```3266 [Thread-24-foo-executor[6 6]] INFO  bar - 2016-11-17 14:48:59,020 INFO foo```
component knows itself! but logs as another component
this happens whether i set component's name explicitly in topology creation or not

**Comment by dan-blanchard** [comment]
Could you please share the code you're using to setup the logging? It's very hard to know what's going on here without more information, as I haven't been able to reproduce this behavior.

**Comment by codywilbourn** [comment]
This issue is a year old at this point, and there have been several releases since this which may have fixed the issue even though Dan was unable to reproduce. If this is still affecting you in the latest release please re-open and let us know.
