### ISSUE TITLE
Question: How to to submit to docker cluster?

### ISSUE THREAD

**Issue by aminalaee** [Parsely/streamparse#352]
I'm trying to deploy docker clusters using the default image [here](https://hub.docker.com/_/storm/). Is there a way to submit directly to the docker? 
The Official storm docker suggests `docker run -it -v $(pwd)/storm-starter-topologies-1.0.2.jar:/topology.jar storm:1.0.2 storm jar /topology.jar org.apache.storm.starter.ExclamationTopology` but how can I use it in python?

**Comment by fedelemantuano** [comment]
Hi @aminalaee I use docker too for my project. I built my own image of **[apache storm](https://hub.docker.com/r/fmantuano/apache-storm/)** image with base `phusion/baseimage` that allows to start script at startup time.
I can't submit the topology at startup, but if you submit the topology with `docker exec` and then you restart the docker the topology will be up.
In my docker I prebuild the jar with `sparse jar -s`. See [this](https://github.com/SpamScope/spamscope-dockerfile-elasticsearch). Did you try to submit it? If you will find a solution can you share it?

**Comment by aminalaee** [comment]
I haven't really tried anything, yet. I was thinking of maybe using the default sparse submit command with [Docker Fabric](https://github.com/merll/docker-fabric) and tweak the config.json . What do you think?

**Comment by fedelemantuano** [comment]
Ok thanks. I don't know docker fabric, but I can't try it and give you feedback.

**Comment by aminalaee** [comment]
@fedelemantuano  I guess it will need some changes in the submit flow. Thank you.

**Comment by jaredlaney** [comment]
Any possible updates here?

**Comment by jaredlaney** [comment]
Would another option be to install all of the python requirements on a base image of all the storm nodes and then use:

    "use_virtualenv": false,
    "install_virtualenv": false,

to tell streamparse that you don't need it to install or use a virtualenv?  Then, maybe you could just submit locally on the nimbus container?

**Comment by dan-blanchard** [comment]
> I'm also trying the "sparse jar -s" command to output the jar but when submitting the topology, I'm not sure what the class name would be to submit...?

`sparse submit` does a bit more work than just build the JAR. It has to tell Storm/Nimbus what the topology actually looks like, so you'd be missing that piece. The JAR is only really usable by `sparse submit`.

I'm not familiar enough with Docker Fabric (or really even Docker itself) to know exactly what you need to do, but if you could get things setup such that you can connect to the container running Nimbus, then you'd be able to just use `sparse submit` like normal (assuming you set up your config properly with `use_virtualenv` and `install_virtualenv` set to `False` like you mentioned).

**Comment by dan-blanchard** [comment]
I should have included this in my info yesterday, but you also would want to set `use_ssh_for_nimbus` to `False`, which would make it so you don't actually need SSH configured for your Nimbus node. You'd just need the port open that Nimbus is listening on.

**Comment by dan-blanchard** [comment]
You can see some info about the `use_ssh_for_nimbus` setting and the reasoning behind it's addition in #96.
