### ISSUE TITLE
Unable to run kafka-jvm example

### ISSUE THREAD

**Issue by kunalgupta22** [Parsely/streamparse#358]
Hi,

I am trying to run kafkaspout example but unable to run it.

When I run last command sparse run, it throws an error. Please help me out in executing topology.

Error:-

Cleaning from prior builds...
Creating topology Uber-JAR...

Warning: local() encountered an error (return code 1) while executing 'lein uberjar'

Traceback (most recent call last):
  File "/home/kunal/virtual_envs/storm_python/bin/sparse", line 11, in <module>
    sys.exit(main())
  File "/home/kunal/virtual_envs/storm_python/local/lib/python2.7/site-packages/streamparse/cli/sparse.py", line 79, in main
    args.func(args)
  File "/home/kunal/virtual_envs/storm_python/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 86, in main
    env_name=args.environment)
  File "/home/kunal/virtual_envs/storm_python/local/lib/python2.7/site-packages/streamparse/cli/run.py", line 45, in run_local_topology
    topology_jar = jar_for_deploy(simple_jar=False)
  File "/home/kunal/virtual_envs/storm_python/local/lib/python2.7/site-packages/streamparse/cli/jar.py", line 38, in jar_for_deploy
    res.stderr))
RuntimeError: Unable to run 'lein uberjar'!
STDOUT:

STDERR:
Compiling 1 source files to /home/kunal/Projects/streamparse/examples/kafka-jvm/_build/classes
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:3: error: package storm.kafka does not exist
import storm.kafka.SpoutConfig;
                  ^
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:4: error: package storm.kafka does not exist
import storm.kafka.KafkaSpout;
                  ^
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:5: error: package storm.kafka does not exist
import storm.kafka.StringScheme;
                  ^
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:6: error: package storm.kafka does not exist
import storm.kafka.ZkHosts;
                  ^
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:7: error: package backtype.storm.spout does not exist
import backtype.storm.spout.SchemeAsMultiScheme;
                           ^
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:9: error: cannot find symbol
public class PixelSpout extends KafkaSpout {
                                ^
  symbol: class KafkaSpout
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:11: error: cannot find symbol
	public PixelSpout(SpoutConfig spoutConf) {
	                  ^
  symbol:   class SpoutConfig
  location: class PixelSpout
/home/kunal/Projects/streamparse/examples/kafka-jvm/src/java/pixelcount/spouts/PixelSpout.java:19: error: cannot find symbol
	public static SpoutConfig defaultSpoutConfig() {
	              ^
  symbol:   class SpoutConfig
  location: class PixelSpout
8 errors
Compilation of Java sources(lein javac) failed.

**Comment by victorpoluceno** [comment]
Hey, the storm package name was from `kafka` to `org.apache.storm` from 0.10 to 1.X release. Changing to the right import and it should work.

**Comment by codywilbourn** [comment]
Victor - Thanks for answering this question.

Kunal - Please re-open this issue if Victor's answer didn't solve your problem.
