### ISSUE TITLE
Add `sparse monitor` command that utilizes `storm monitor`

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#36]
Pull request 117 against Storm added the `storm monitor` command, which monitors topology throughput in the console:

https://github.com/apache/incubator-storm/pull/117

We should add an `sparse monitor` equivalent that issues the `storm monitor` command similarly to how we wrapped up StormSubmitter functionality for `sparse submit`.

**Comment by dan-blanchard** [comment]
#52 has been merged, so I'm closing this.
