### ISSUE TITLE
No such file: quickstart

### ISSUE THREAD

**Issue by shubhamagarwal003** [Parsely/streamparse#372]
I am new to apache storm and sparse. When I tried to create the sample wordcount project using "sparse quickstart wordcount", it gives the error No such file: quickstart. What I am missing here? Can someone help?

**Comment by dan-blanchard** [comment]
@shubhamagarwal003 It sounds to me like maybe you have another command called `sparse` installed on your system, because this works fine for me. If this was a streamparse issue, you would get a full traceback. If you can provide one, that would be helpful.

**Comment by shubhamagarwal003** [comment]
@dan-blanchard  thanks for the reply. I indeed had a different sparse. When I used streamparse outside a virtualenv it says sparse is not installed. So I installed it using "apt install sparse". 
But when I used streamparse in the virtaulenv everything works fine. Though I am not sure why does creation of virtualenv resolved this.
