### ISSUE TITLE
[Question] Worker crashed with 'Cannot run program "streamparse_run" '

### ISSUE THREAD

**Issue by caden714** [Parsely/streamparse#375]
I'm having an issue running wordcount on the single storm. 'sparse run/submit' works well. After submitting to the cluster, the worker ran into the exception as below. The cluster is running on storm 1.0.3 python2.7.
So appreciated it if can get any clue. Thanks

Exception in the worker logs: 
https://gist.github.com/caden714/f1f7ab37751a8784713de15eb1d58241
Caused by: java.io.IOException: Cannot run program "streamparse_run" (in directory "/usr/local/src/das/apache-storm-1.0.3/storm-local/supervisor/stormdi
st/wordcount-8-1496872394/resources"): error=2, No such file or directory

config.json
------
{
    "serializer": "json",
    "topology_specs": "topologies/",
    "virtualenv_specs": "virtualenvs/",
    "envs": {
        "prod": {
            "user": "xxx",
            "nimbus": "127.0.0.1",
            "workers": [
                "127.0.0.1"
            ],
            "virtualenv_root": "/home/xxxx/virtualenvs",
            "log": {
                "path": "/var/log/storm/xxx/",
                "file": "pystorm_{topology_name}_{component_name}_{task_id}_{pid}.log",
                "max_bytes": 100000,
                "backup_count": 10,
                "level": "info"
            },
            "use_ssh_for_nimbus": false,
            "use_virtualenv": false
        }
    }
}

**Comment by dan-blanchard** [comment]
If you have `use_virtualenv` set to `false`, you have to make sure `streamparse_run` is in the `storm` user's `PATH`. 

I also notice that you're setting `virtualenv_root`, but then setting and `use_virtualenv` to `false`, which is a little confusing. `virtualenv_root` won't be used at all if you have `use_virtualenv` disabled.
