### ISSUE TITLE
Idea: change how `sparse run` deals with verbose/debug output

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#39]
A member of Parse.ly's team, @dfdeshom, thought that the behavior of `sparse run` was a little confusing, because it includes debug output for initialization of the Storm topology, but doesn't include debug output for the Python layer or tuples being emitted throughout the topology. For that, you need to flip on `--debug` or `-d`, which will enable Storm's topology debug mode.

His suggestion is that we should either make `-d` flipped on by default, or make `sparse run`'s default output mostly silent, perhaps only saying things like "Running topology..." and "Topology completed running."

He also thought that we should somehow catch uses of the "print" keyword and issue warnings so users know that you can't actually use "print" within Storm bolts/spouts due to the way ShellBolts work.

It'd be great to get some opinions from the community on this. @dan-blanchard, do you have any thoughts, since you recently tried streamparse out for yourself?

**Comment by rduplain** [comment]
`sparse run -d` includes all emitted values, which is too much logging for the default.(particularly if payloads are dense). That said, +1 to the proposal to silence noisy output in the default mode while improving `print` experience.

**Comment by dan-blanchard** [comment]
`sparse run` has been temporarily removed entirely, so this isn't really valid anymore.  See #213.
