### ISSUE TITLE
Broken `sparse run` functionality after the 3.7.0 upgrade!

### ISSUE THREAD

**Issue by muhammad-alaref** [Parsely/streamparse#391]
The last update (version 3.7.0) broke the `sparse run` functionality!
Running the example from the [Quickstart](http://streamparse.readthedocs.io/en/stable/quickstart.html) guide it gives an error message.

![screenshot_20170826_112345](https://user-images.githubusercontent.com/17222903/29740189-1c0eda54-8a51-11e7-9276-c46653396d3c.png)

Since `sparse run` should run the topology locally, it should not look for Nimbus.

When I downgraded the package to version 3.6.0 everything was back no normal :smile:

**Comment by amontalenti** [comment]
@muhammad-alaref Thanks for reporting this. Clearly a regression. Our team will take a look at this early next week.

**Comment by dan-blanchard** [comment]
The issue here was that `sparse run` was trying to connect to Nimbus in `streamparse.util.resolve_options`, so it was only broken if Nimbus wasn't configured in your `config.json`. That said, PR #392 to fix the issue will be merged shortly and then I'll release 3.7.1 on PyPI.
