### ISSUE TITLE
Consider dropping invoke and just using fabric for everything (or stop using SSH).

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#45]
Invoke is just Yet Another Moving Part, and maybe causes confuses on where you should look for tasks. We could merge all the invoke tasks into the basic fabfile.py and get rid of tasks.py from the directory layout altogether. (suggested by @dan-blanchard)

**Comment by rduplain** [comment]
Alternatives: use [paramiko](http://www.paramiko.org/) directly instead, or stop using SSH altogether.

@dan-blanchard says:

> I'd rather see us ditch trying to SSH into machines at all and rely on Storm's hook support to run a little JVM code that sets up the virtualenv. See our discussion here: https://github.com/Parsely/streamparse/issues/99#issuecomment-94007564 #99

**Comment by rduplain** [comment]
@dan-blanchard says:

> SSH is entirely optional at this point. You can set use_ssh_for_nimbus and use_virtualenv to False in config.json and you won't need to SSH into anything. This is described here http://streamparse.readthedocs.org/en/stable/quickstart.html?highlight=use_virtualenv#disabling-virtualenv-creation
>
> We rely on the REST API for getting stats, and sparse list/kill will only use ssh if use_ssh_for_nimbus is set. The only commands we have that definitely would use SSH right now are remove_logs, tail, and update_virtualenv. We could likely hook into the REST API's newly provided access to logs to handle tail for us (and not worry about remove_logs), which would only leave update_virtualenv, which should be replaced by the hook approach I mentioned before.

**Comment by dan-blanchard** [comment]
I dropped `invoke` from the requirements, now that `fabric3` is Python 3 compatible
