### ISSUE TITLE
'sparse submit' should use the user's existing ssh config file

### ISSUE THREAD

**Issue by asasturkar** [Parsely/streamparse#54]
This allows sparse to reuse any user configured ssh keys.

This requires the addition of a single line to the streamparse/ext/fabric.py file, to the activate_env function.

```python
env.use_ssh_config = True
```

**Comment by hadisotudeh** [comment]
I've added "from fabric.api import env env.use_ssh_config = True" to the fabfile.py, but I get the following error when I ran the "sparse submit" command
Deploying "topology" topology...
bind: Cannot assign requested address
ssh tunnel to Nimbus 127.0.0.1:6627 established.
Routing Python logging to None.
Running lein command to submit topology to nimbus:
lein run -m streamparse.commands.submit_topology/-main topologies/topology.clj --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'topology.python.path="/home/hadi/Desktop/Storm//topology/bin/python2.7"'
{:option {topology.python.path /home/hadi/Desktop/Storm//topology/bin/python2.7, topology.acker.executors 2, topology.workers 2}, :debug false, :port 6627, :host localhost, :help false}
channel 1016: open failed: administratively prohibited: open failed
channel 1017: open failed: administratively prohibited: open failed
Caught exception: org.apache.thrift7.transport.TTransportException
What should I do?

**Comment by msukmanowsky** [comment]
@hadisotudeh see http://unix.stackexchange.com/questions/14160/ssh-tunneling-error-channel-1-open-failed-administratively-prohibited-open and in the future, for SSH errors, try Googling the error first (found this just by Googling "channel 1016: open failed: administratively prohibited: open failed").

**Comment by hadisotudeh** [comment]
yes, I've searched before, but the problem didn't solve and I thought maybe this problem is special for streamparse projects.

**Comment by dan-blanchard** [comment]
I agree with @amontalenti and made this happen by default [now](https://github.com/Parsely/streamparse/commit/62aaf27d2c7320dfaa41459ba8f07a618517a398#diff-f9cea264aa6f8d7e0cc79622e0592e2fL17).
