### ISSUE TITLE
Implement vesion scheme for org.parsely/streamparse Clojure interop library

### ISSUE THREAD

**Issue by kbourgoin** [Parsely/streamparse#59]
We don't update the clojure lib often, but the current is 0.0.4-SNAPSHOT whereas the python lib is at 1.0.1. This is pretty confusing, and the two versions should ideally match.

**Comment by dan-blanchard** [comment]
@amontalenti pointed out to me yesterday that if we drop the SNAPSHOT monicker, we can't guarantee that all existing streamparse deployments will get the updated version of the Clojure library, so I think I'm going to just close this issue.  Will re-open if there are strong objections.
