### ISSUE TITLE
Clean up the examples/ folder

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#63]
There is some old cruft in this folder. We also have some new examples (e.g. using official Kafka spout via Clojure) that are worth highlighting. I added a nice simple example of an upgraded project that does WordCount using Redis:

https://github.com/Parsely/streamparse/tree/master/examples/redis

I also wonder what our general approach to `examples/` should be. Should we just avoid storing these in the repo and instead including the useful ones as "templates" for `sparse quickstart`? Or relocate to another `streamparse-examples` repo and have `sparse quickstart` download its bootstrap stuff directly from Github? I'm not sure what a good approach is here. There must be some other project that we can copy. :grin:

**Comment by rduplain** [comment]
Update: https://github.com/Parsely/birding is built as an example project, complete with docs.

**Comment by dan-blanchard** [comment]
I will also mention that the Kafka JVM example's included [Vagrant VM](https://github.com/Parsely/streamparse/blob/f4ec2383277fcc5172313c2585d23b653f153306/examples/kafka-jvm/Vagrantfile) is one of my main tools for developing streamparse these days.  We might want to mention that somewhere in the dev docs, if we don't already.
