### ISSUE TITLE
Break --par into two options

### ISSUE THREAD

**Issue by dan-blanchard** [Parsely/streamparse#74]
Currently you can only set the number of Java workers and the number of acker executors to the same thing with `sparse --par`.  Some topologies do not require the Storm reliability layer, and a common way to disable it is to set the number of ackers to 0 (see the "Tuning Reliability" section of [this page](http://storm.apache.org/documentation/Guaranteeing-message-processing.html)).  It would be nice if there was a way to do this with `sparse`.

**Comment by codywilbourn** [comment]
@dan-blanchard @amontalenti Initially I'm thinking we should keep --par, at least for a little while. We can add -a/--ackers and -w/--workers (too similar to --wait?) to set ackers & workers independently. The precedence setting would be workers over par and ackers over par.

**Comment by dan-blanchard** [comment]
I'm fine with keeping `--par` if there were separate options for `--ackers` and `--workers`.  I know not everyone cares about setting them independently.

**Comment by dan-blanchard** [comment]
Fixed by #97.
