### ISSUE TITLE
`sparse` broken on Python 3.4

### ISSUE THREAD

**Issue by blbradley** [Parsely/streamparse#76]
I received this error: fabric/fabric#1050.

This is because streamparse uses a branch from fabric with Python 3.3 support.  Full support for Python 3 won't come until fabric 2 [documented in fabric's roadmap](http://www.fabfile.org/en/latest/roadmap.html#invoke-fabric-2-x-and-patchwork).

Both `sparse quickstart` and `sparse run` have this issue.

**Comment by dan-blanchard** [comment]
I'm going to revise my statement here and say that `sparse submit` works fine for Python 3.4 if you're using the fork we have in requirements.txt, and I think the issue I had before was unrelated to 3.4.
