### ISSUE TITLE
Support Storm's custom serialization support for multi-lang. [msgpack]

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#8]
A recently [merged pull request 84 on the Storm project][merged] implements custom serialization support for the multi-lang protocol. This means that you can technically register other faster serializers than JSON for Storm's tuple data, e.g. we could use [msgpack][msgpack].

In addition, thanks to Storm's built-in support for serialization hooks with Kyro, we could actually switch Tuple serialization from Kyro's built-in JVM-based serializer to something like msgpack. This would potentially allow us to avoid the encode/decode cost associated with using ShellBolts and ShellSpouts.

It would be great for someone from the community to do a prototype of this using a streamparse project, and prove its viability. Then we could merge the support into the core library, build a support library in Java for the custom serializers, and offer documentation for how to set up Storm to leverage them. This will likely fit in very well with our lein-based Storm project management.

[merged]: https://github.com/apache/incubator-storm/pull/84
[msgpack]: http://msgpack.org/

**Comment by rduplain** [comment]
Related to #174.

**Comment by dan-blanchard** [comment]
pystorm/pystorm#1 addresses this.

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#5
