### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by hadisotudeh** [Parsely/streamparse#80]
Hi,
I've the following problem when trying to run "sparse run -d" command:

Running wordcount topology...
Routing Python logging to /home/hadi/STORM/wordcount/logs.
Running lein command to run local cluster:
lein run -m streamparse.commands.run/-main topologies/wordcount.clj -t 5 --debug --option 'topology.workers=2' --option 'topology.acker.executors=2' --option 'streamparse.log.path="/home/hadi/STORM/wordcount/logs"' --option 'streamparse.log.level="debug"'
Nov 30, 2014 11:14:16 AM org.apache.http.impl.client.DefaultHttpClient tryConnect
INFO: I/O exception (java.net.SocketException) caught when connecting to {s}->https://clojars.org: Network is unreachable

I think there is no internet connection problem, there is any problem in the host?
Can somebody help me?
Best

**Comment by amontalenti** [comment]
Couldn't get an answer for this issue or a repro; closing.
