### ISSUE TITLE
Upgrade multi-lang implementation which may have broken in Storm 0.9.3

### ISSUE THREAD

**Issue by amontalenti** [Parsely/streamparse#82]
[Storm 0.9.3 release notes](https://storm.apache.org/2014/11/25/storm093-released.html) indicate that "the multi-lang API has changed in a non-backward-compatible way". This has something to do with the way that ShellBolts implement heartbeat'ing / sync'ing. Should test, investigate, and upgrade as necessary the ipc module.

**Comment by dan-blanchard** [comment]
I should note that #87 made it so we're compatible with 0.9.3, but we're still not taking advantage of the ability to have custom metrics reported to Nimbus like was added in apache/storm#38. That should probably be a separate issue though.
