### ISSUE TITLE
run locally streamparse Error

### ISSUE THREAD

**Issue by hadisotudeh** [Parsely/streamparse#85]
[hadi@hadi STORM]$ sparse quickstart word

Creating your word streamparse project...
...
...
...

then I ran this command: cd word
                                        sparse run

...

but the result is :

6509 [Thread-9-count-bolt] INFO  backtype.storm.util - Halting process: ("Worker died")
Traceback (most recent call last):
  File "/usr/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==1.0.1', 'console_scripts', 'sparse')()
  File "/usr/lib/python2.7/site-packages/streamparse/cmdln.py", line 82, in main
    run_local_topology(args["--name"], time, par, options, args["--debug"])
  File "/usr/lib/python2.7/site-packages/invoke/tasks.py", line 111, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/streamparse/ext/invoke.py", line 170, in run_local_topology
    run(full_cmd)
  File "/usr/lib/python2.7/site-packages/invoke/runner.py", line 160, in run
    raise Failure(result)
invoke.exceptions.Failure: Command execution failure!

What should I do?

**Comment by wilsoncao** [comment]
I have the same problem with you, any idea to solve it?

**Comment by amontalenti** [comment]
This part of your log output:

    /usr/bin/python: Error while finding spec for 'streamparse.run'

Indicates that when `python -m streamparse.run` is attempting to be run, it is not succeeding because 'streamparse' is not available in your PYTHONPATH. The reason for this is probably that you don't have your virtualenv that includes a streamparse installation properly activated, I think. Closing.
