### ISSUE TITLE
`sparse` broken on Python 3.3

### ISSUE THREAD

**Issue by hadisotudeh** [Parsely/streamparse#86]
Hi, I've run the sparse command in the terminal and get the following result:

```pytb
[hadi@hadi Desktop]$ sparse
Traceback (most recent call last):
  File "/usr/bin/sparse", line 9, in <module>
    load_entry_point('streamparse==1.0.1', 'console_scripts', 'sparse')()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2184, in load
    ['__name__'])
  File "/usr/lib/python3.3/site-packages/streamparse/__init__.py", line 11, in <module>
    import streamparse.cmdln
  File "/usr/lib/python3.3/site-packages/streamparse/cmdln.py", line 6, in <module>
    from .ext.invoke import (list_topologies, kill_topology, run_local_topology,
  File "/usr/lib/python3.3/site-packages/streamparse/ext/invoke.py", line 27, in <module>
    from .fabric import activate_env, create_or_update_virtualenvs, tail_logs
  File "/usr/lib/python3.3/site-packages/streamparse/ext/fabric.py", line 17, in <module>
    from fabric.api import env, execute, parallel, prefix, put, puts, run, task
  File "/usr/lib/python3.3/site-packages/fabric/api.py", line 9, in <module>
    from fabric.context_managers import (cd, hide, settings, show, path, prefix,
  File "/usr/lib/python3.3/site-packages/fabric/context_managers.py", line 535
    def accept(channel, (src_addr, src_port), (dest_addr, dest_port)):
                        ^
SyntaxError: invalid syntax
```

What should I do?

**Comment by ysimonson** [comment]
I'm having the same problem. Here's been my experience so far getting started with streamparse.

1) Install streamparse: `pip3 install streamparse` -- using pip3 b/c we use python 3 in production
2) Get the SyntaxError, so I manually install the fabric fork: `pip3 install -e git+https://github.com/pashinin/fabric@p33#egg=fabric`. This works and fixes the error.
3) Run it and get the same second error (`No module named 'streamparse'`).

It's trying to run the scripts via the system python installation at `/usr/bin/python`, where streamparse is not installed. If I symlinked like @hadisotudeh, it would almost certainly break my setup, as OS X expects python 2.

Is it storm or streamparse that's referencing system python? Is there a way to change it?

**Comment by dan-blanchard** [comment]
I would recommend setting up an [Anaconda Python 3 installation](http://continuum.io/downloads) so that it is completely isolated from the OS X system Python.  That's what I do.

**Comment by ysimonson** [comment]
But streamparse is referencing system python, so that won't fix anything right?

**Comment by dan-blanchard** [comment]
No, streamparse does not use the system Python installation.  It will use whichever Python the virtual/conda environment you have it installed in uses.

**Comment by omus** [comment]
You could also use [pyenv](https://github.com/yyuu/pyenv) which is available from Homebrew.

**Comment by vlad-dragos** [comment]
Hello,

So from my understanding streamparse only works with python3.3? (no 3.4 support)?

**Comment by dan-blanchard** [comment]
I should work with 3.3 or 3.4 (probably even 3.2).  The key is that you just don't want to use the system Python installation on OS X.

**Comment by vlad-dragos** [comment]
@dan-blanchard I'm not. I'm using the version for Homebrew. I will do some more research and if I find anything worth sharing I will post an update here. :)

**Comment by ysimonson** [comment]
Yeah, this worked for me: 

    virtualenv -p python3.4 venv
    source venv/bin/activate
    pip install streamparse
    pip install -e git+https://github.com/pashinin/fabric@p33#egg=fabric
    sparse

**Comment by vlad-dragos** [comment]
Thx @ysimonson it works using the snippet you provided. Maybe this should be added to the documenation? Under Dependencies?
