### ISSUE TITLE
Better/Flexible logging support

### ISSUE THREAD

**Issue by vishalsurana** [Parsely/streamparse#89]
Current logging support in streamparse could be more helpful when troubleshooting issues. While the logs are split into files for each bolt/spout, when things go wrong, its not clear as to where in the code a problem occurred. It would be better if the logger could emit the function name and the line number of the code along with the log message. 

However, this cannot be controlled by users as the formatter configuration is hardcoded like so (refer ipc.py):

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

Worse, python logger does not allow us to fetch a logger's handler and set/modify its formatter. Thus, I would suggest that we change the logging format to this:

formatter = logging.Formatter("%(levelname)s %(asctime)s %(module)s:%(lineno)s %(funcName)s %(message)s")

If changing the code as above is not desirable, then the formatter string could become a configurable option. I believe that debugging issues will become significantly easier with this change.

**Comment by westover** [comment]
What about a trigger for using the Traceback module in Python to pass up full traceback. Maybe like a development or debug mode that could use that?

**Comment by dan-blanchard** [comment]
This issue was moved to pystorm/pystorm#7
